sonar.projectKey=Sojisoyoye_heimpath
sonar.organization=sojisoyoye

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.exclusions=backend/alembic/**,frontend/src/client/**,frontend/node_modules/**,**/__pycache__/**,**/*.pyc

sonar.python.version=3.10
sonar.python.coverage.reportPaths=backend/coverage.xml
