// This file is auto-generated by @hey-api/openapi-ts

/**
 * Single activity entry for the timeline.
 */
export type ActivityItem = {
    activity_type: ActivityType;
    title: string;
    description: string;
    entity_id: string;
    timestamp: string;
};

/**
 * Types of user activity tracked on the dashboard.
 */
export type ActivityType = 'journey_started' | 'step_completed' | 'document_uploaded' | 'calculation_saved' | 'roi_calculated' | 'financing_assessed' | 'law_bookmarked';

/**
 * JWT token response with access and refresh tokens.
 */
export type AuthToken = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
};

/**
 * Request schema for batch text translation.
 */
export type BatchTranslationRequest = {
    /**
     * List of texts to translate
     */
    texts: Array<(string)>;
    /**
     * Source language code
     */
    source_language?: SupportedLanguage;
    /**
     * Target language code
     */
    target_language?: SupportedLanguage;
    /**
     * Include warnings for legal/financial terms
     */
    include_legal_warnings?: boolean;
};

/**
 * Response schema for batch text translation.
 */
export type BatchTranslationResponse = {
    /**
     * List of translation results
     */
    translations: Array<TranslationResponse>;
    /**
     * Total characters translated
     */
    total_character_count: number;
    /**
     * Total number of legal warnings
     */
    total_warnings: number;
};

export type Body_documents_upload_document = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Request schema for creating a bookmark.
 */
export type BookmarkCreate = {
    notes?: (string | null);
};

/**
 * Brief bookmarked law info for dashboard lists.
 */
export type BookmarkedLawSummary = {
    id: string;
    citation: string;
    title_en: string;
    category: string;
    bookmarked_at: string;
};

/**
 * List of user bookmarks.
 */
export type BookmarkListResponse = {
    data: Array<BookmarkResponse>;
    count: number;
};

/**
 * Response schema for a bookmark.
 */
export type BookmarkResponse = {
    id: string;
    law_id: string;
    notes?: (string | null);
    created_at: string;
    law: LawSummary;
};

/**
 * Response with checkout session details.
 */
export type CheckoutResponse = {
    session_id: string;
    url: string;
};

/**
 * Default cost percentages used in calculations.
 */
export type CostDefaults = {
    notary_fee_percent: number;
    land_registry_fee_percent: number;
    agent_commission_percent: number;
};

/**
 * Response schema for court rulings.
 */
export type CourtRulingResponse = {
    court_name: string;
    case_number: string;
    ruling_date: string;
    title: string;
    summary: string;
    significance?: (string | null);
    source_url?: (string | null);
    id: string;
};

/**
 * Request to create a checkout session.
 */
export type CreateCheckoutRequest = {
    tier: SubscriptionTier;
    success_url: string;
    cancel_url: string;
};

/**
 * Aggregated dashboard data for the authenticated user.
 */
export type DashboardOverviewResponse = {
    journey?: (JourneyOverview | null);
    has_journey: boolean;
    recent_documents: Array<SavedDocumentSummary>;
    recent_calculations: Array<SavedCalculationSummary>;
    bookmarked_laws: Array<BookmarkedLawSummary>;
    recent_activity: Array<ActivityItem>;
    documents_translated_this_month: number;
    total_calculations: number;
    total_bookmarks: number;
};

/**
 * A legal clause detected in the document.
 */
export type DetectedClause = {
    /**
     * Type: purchase_price, deadline, warranty_exclusion, special_condition, financial_term
     */
    clause_type: string;
    original_text: string;
    translated_text: string;
    page_number: number;
    /**
     * Risk level: low, medium, high
     */
    risk_level: string;
};

/**
 * Full document detail with optional translation.
 */
export type DocumentDetailResponse = {
    id: string;
    original_filename: string;
    file_size_bytes: number;
    page_count: number;
    document_type: DocumentTypeEnum;
    status: DocumentStatusEnum;
    error_message?: (string | null);
    created_at: string;
    translation?: (DocumentTranslationResponse | null);
};

/**
 * Paginated list of documents.
 */
export type DocumentListResponse = {
    data: Array<DocumentSummary>;
    total: number;
    page: number;
    page_size: number;
};

/**
 * Risk warning for a term in the document.
 */
export type DocumentRiskWarning = {
    original_term: string;
    translated_term: string;
    risk_level: string;
    explanation: string;
    page_number?: (number | null);
};

/**
 * Document processing status choices.
 */
export type DocumentStatusEnum = 'uploaded' | 'processing' | 'completed' | 'failed';

/**
 * Lightweight status check response.
 */
export type DocumentStatusResponse = {
    id: string;
    status: DocumentStatusEnum;
    error_message?: (string | null);
    page_count: number;
};

/**
 * Summary of a document for list views.
 */
export type DocumentSummary = {
    id: string;
    original_filename: string;
    file_size_bytes: number;
    page_count: number;
    document_type: DocumentTypeEnum;
    status: DocumentStatusEnum;
    created_at: string;
};

/**
 * Full translation result for a document.
 */
export type DocumentTranslationResponse = {
    id: string;
    document_id: string;
    source_language: string;
    target_language: string;
    translated_pages: Array<TranslatedPage>;
    clauses_detected: Array<DetectedClause>;
    risk_warnings: Array<DocumentRiskWarning>;
    processing_started_at?: (string | null);
    processing_completed_at?: (string | null);
};

/**
 * Document type choices.
 */
export type DocumentTypeEnum = 'kaufvertrag' | 'mietvertrag' | 'expose' | 'nebenkostenabrechnung' | 'grundbuchauszug' | 'teilungserklaerung' | 'hausgeldabrechnung' | 'unknown';

/**
 * Response after uploading a document.
 */
export type DocumentUploadResponse = {
    id: string;
    original_filename: string;
    file_size_bytes: number;
    page_count: number;
    document_type: DocumentTypeEnum;
    status: DocumentStatusEnum;
};

/**
 * Request to create a financing eligibility assessment.
 */
export type FinancingAssessmentCreate = {
    name?: (string | null);
    /**
     * Current employment type
     */
    employment_status: 'permanent' | 'fixed_term' | 'self_employed' | 'freelance' | 'civil_servant';
    /**
     * Years in current employment
     */
    employment_years: number;
    /**
     * Monthly net income in EUR
     */
    monthly_net_income: number;
    /**
     * Monthly debt obligations in EUR
     */
    monthly_debt: number;
    /**
     * Available down payment in EUR
     */
    available_down_payment: number;
    /**
     * SCHUFA credit rating category
     */
    schufa_rating: 'excellent' | 'good' | 'satisfactory' | 'adequate' | 'poor' | 'unknown';
    /**
     * Residency status in Germany
     */
    residency_status: 'german_citizen' | 'eu_citizen' | 'permanent_resident' | 'temporary_resident' | 'non_eu';
};

/**
 * Current employment type
 */
export type employment_status = 'permanent' | 'fixed_term' | 'self_employed' | 'freelance' | 'civil_servant';

/**
 * SCHUFA credit rating category
 */
export type schufa_rating = 'excellent' | 'good' | 'satisfactory' | 'adequate' | 'poor' | 'unknown';

/**
 * Residency status in Germany
 */
export type residency_status = 'german_citizen' | 'eu_citizen' | 'permanent_resident' | 'temporary_resident' | 'non_eu';

/**
 * List of saved financing assessments.
 */
export type FinancingAssessmentListResponse = {
    data: Array<FinancingAssessmentSummary>;
    count: number;
};

/**
 * Full response for a saved financing assessment.
 */
export type FinancingAssessmentResponse = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    employment_status: string;
    employment_years: number;
    monthly_net_income: number;
    monthly_debt: number;
    available_down_payment: number;
    schufa_rating: string;
    residency_status: string;
    employment_score: number;
    income_ratio_score: number;
    down_payment_score: number;
    schufa_score: number;
    residency_score: number;
    years_bonus_score: number;
    total_score: number;
    likelihood_label: string;
    max_loan_estimate: number;
    recommended_down_payment_percent: number;
    expected_rate_min: number;
    expected_rate_max: number;
    ltv_ratio: number;
    strengths: Array<(string)>;
    improvements: Array<(string)>;
    document_checklist: Array<(string)>;
    created_at: string;
};

/**
 * Summary for list views.
 */
export type FinancingAssessmentSummary = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    total_score: number;
    likelihood_label: string;
    max_loan_estimate: number;
    created_at: string;
};

/**
 * Types of financing.
 */
export type FinancingType = 'cash' | 'mortgage' | 'mixed';

/**
 * Request to save a hidden cost calculation.
 */
export type HiddenCostCalculationCreate = {
    name?: (string | null);
    /**
     * Property price in EUR
     */
    property_price: number;
    /**
     * German state code
     */
    state_code: string;
    property_type: string;
    include_agent?: boolean;
    renovation_level?: 'none' | 'light' | 'medium' | 'full';
    include_moving?: boolean;
};

export type renovation_level = 'none' | 'light' | 'medium' | 'full';

/**
 * Paginated list of saved calculations.
 */
export type HiddenCostCalculationListResponse = {
    data: Array<HiddenCostCalculationSummary>;
    count: number;
};

/**
 * Full response for a saved calculation.
 */
export type HiddenCostCalculationResponse = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    property_price: number;
    state_code: string;
    property_type: string;
    include_agent: boolean;
    renovation_level: string;
    include_moving: boolean;
    transfer_tax: number;
    notary_fee: number;
    land_registry_fee: number;
    agent_commission: number;
    renovation_estimate: number;
    moving_costs: number;
    total_additional_costs: number;
    total_cost_of_ownership: number;
    additional_cost_percentage: number;
    created_at: string;
};

/**
 * Summary for list views.
 */
export type HiddenCostCalculationSummary = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    property_price: number;
    state_code: string;
    total_additional_costs: number;
    total_cost_of_ownership: number;
    created_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * Schema for item data in export.
 */
export type ItemExport = {
    id: string;
    title: string;
    description?: (string | null);
    created_at: string;
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Schema for creating a journey from questionnaire.
 */
export type JourneyCreate = {
    title?: string;
    questionnaire: QuestionnaireAnswers;
};

/**
 * Detailed journey response with full step data.
 */
export type JourneyDetailResponse = {
    id: string;
    title: string;
    current_phase: JourneyPhase;
    current_step_number: number;
    property_type?: (PropertyType | null);
    property_location?: (string | null);
    financing_type?: (FinancingType | null);
    is_first_time_buyer: boolean;
    has_german_residency: boolean;
    budget_euros?: (number | null);
    target_purchase_date?: (string | null);
    property_goals?: (PropertyGoals | null);
    started_at?: (string | null);
    completed_at?: (string | null);
    is_active: boolean;
    created_at: string;
    steps?: Array<JourneyStepResponse>;
};

/**
 * Summary of user's active journey for dashboard display.
 */
export type JourneyOverview = {
    id: string;
    title: string;
    current_phase: string;
    current_step_number: number;
    progress_percentage: number;
    completed_steps: number;
    total_steps: number;
    estimated_days_remaining?: (number | null);
    started_at?: (string | null);
    next_step_title?: (string | null);
    next_step_id?: (string | null);
    phases: {
        [key: string]: {
            [key: string]: (number);
        };
    };
};

/**
 * Phases of the property buying journey.
 */
export type JourneyPhase = 'research' | 'preparation' | 'buying' | 'closing';

/**
 * Schema for journey progress.
 */
export type JourneyProgressResponse = {
    journey_id: string;
    total_steps: number;
    completed_steps: number;
    current_step_number: number;
    current_phase: JourneyPhase;
    progress_percentage: number;
    estimated_days_remaining?: (number | null);
    phases: {
        [key: string]: {
            [key: string]: (number);
        };
    };
};

/**
 * Schema for journey response.
 */
export type JourneyResponse = {
    id: string;
    title: string;
    current_phase: JourneyPhase;
    current_step_number: number;
    property_type?: (PropertyType | null);
    property_location?: (string | null);
    financing_type?: (FinancingType | null);
    is_first_time_buyer: boolean;
    has_german_residency: boolean;
    budget_euros?: (number | null);
    target_purchase_date?: (string | null);
    property_goals?: (PropertyGoals | null);
    started_at?: (string | null);
    completed_at?: (string | null);
    is_active: boolean;
    created_at: string;
    steps?: Array<JourneyStepSummary>;
};

/**
 * Schema for list of journeys.
 */
export type JourneysListResponse = {
    data: Array<JourneyResponse>;
    count: number;
};

/**
 * Response for laws linked to a journey step.
 */
export type JourneyStepLawResponse = {
    law: LawSummary;
    relevance_score: number;
};

/**
 * List of laws for a journey step.
 */
export type JourneyStepLawsResponse = {
    data: Array<JourneyStepLawResponse>;
    count: number;
    step_content_key: string;
};

/**
 * Schema for journey step response.
 */
export type JourneyStepResponse = {
    step_number: number;
    phase: JourneyPhase;
    title: string;
    description?: (string | null);
    estimated_duration_days?: (number | null);
    id: string;
    status: StepStatus;
    started_at?: (string | null);
    completed_at?: (string | null);
    content_key?: (string | null);
    related_laws?: (string | null);
    estimated_costs?: (string | null);
    tasks?: Array<JourneyTaskResponse>;
};

/**
 * Summary schema for journey step (without tasks).
 */
export type JourneyStepSummary = {
    id: string;
    step_number: number;
    phase: JourneyPhase;
    title: string;
    status: StepStatus;
    estimated_duration_days?: (number | null);
};

/**
 * Schema for updating a journey step status.
 */
export type JourneyStepUpdate = {
    status: StepStatus;
};

/**
 * Schema for journey task response.
 */
export type JourneyTaskResponse = {
    title: string;
    description?: (string | null);
    is_required?: boolean;
    resource_url?: (string | null);
    resource_type?: (string | null);
    id: string;
    order: number;
    is_completed: boolean;
    completed_at?: (string | null);
};

/**
 * Schema for updating a journey task.
 */
export type JourneyTaskUpdate = {
    is_completed: boolean;
};

/**
 * Schema for updating journey metadata.
 */
export type JourneyUpdate = {
    title?: (string | null);
    target_purchase_date?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Request schema for language detection.
 */
export type LanguageDetectionRequest = {
    /**
     * Text to detect language of
     */
    text: string;
};

/**
 * Response schema for language detection.
 */
export type LanguageDetectionResponse = {
    /**
     * Detected language code
     */
    language: string;
    /**
     * Confidence score of detection (0-1)
     */
    confidence: number;
    /**
     * Whether the detected language is supported for translation
     */
    is_supported: boolean;
};

/**
 * Categories for German real estate laws.
 */
export type LawCategory = 'buying_process' | 'costs_and_taxes' | 'rental_law' | 'condominium' | 'agent_regulations';

/**
 * Extended response with related laws.
 */
export type LawDetailResponse = {
    id: string;
    citation: string;
    title_de: string;
    title_en: string;
    category: LawCategory;
    property_type: PropertyTypeApplicability;
    one_line_summary: string;
    short_summary: string;
    detailed_explanation: string;
    real_world_example?: (string | null);
    common_disputes?: (string | null);
    buyer_implications?: (string | null);
    seller_implications?: (string | null);
    landlord_implications?: (string | null);
    tenant_implications?: (string | null);
    original_text_de?: (string | null);
    last_amended?: (string | null);
    change_history?: (string | null);
    created_at: string;
    updated_at: string;
    court_rulings?: Array<CourtRulingResponse>;
    state_variations?: Array<StateVariationResponse>;
    related_laws?: Array<LawSummary>;
    is_bookmarked?: boolean;
};

/**
 * Paginated list of laws.
 */
export type LawListResponse = {
    data: Array<LawSummary>;
    count: number;
    total: number;
    page: number;
    page_size: number;
};

/**
 * Search results response.
 */
export type LawSearchResponse = {
    data: Array<LawSearchResult>;
    count: number;
    query: string;
};

/**
 * Search result with relevance score.
 */
export type LawSearchResult = {
    id: string;
    citation: string;
    title_en: string;
    category: LawCategory;
    one_line_summary: string;
    relevance_score: number;
    matched_fields?: Array<(string)>;
};

/**
 * Summary view of a law for list responses.
 */
export type LawSummary = {
    id: string;
    citation: string;
    title_en: string;
    category: LawCategory;
    property_type: PropertyTypeApplicability;
    one_line_summary: string;
};

/**
 * Warning about a legal or financial term in translation.
 */
export type LegalTermWarning = {
    /**
     * Original term in source language
     */
    original_term: string;
    /**
     * Translated term
     */
    translated_term: string;
    /**
     * Risk level for this term
     */
    risk_level: RiskLevel;
    /**
     * Explanation of why this term requires attention
     */
    explanation: string;
};

/**
 * Schema for login request.
 */
export type LoginRequest = {
    email: string;
    password: string;
    remember_me?: boolean;
};

/**
 * Schema for logout request.
 */
export type LogoutRequest = {
    refresh_token: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Schema for next recommended step.
 */
export type NextStepResponse = {
    has_next: boolean;
    step?: (JourneyStepResponse | null);
    message?: (string | null);
};

/**
 * Request to create a customer portal session.
 */
export type PortalRequest = {
    return_url: string;
};

/**
 * Response with portal session URL.
 */
export type PortalResponse = {
    url: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Single year projection data.
 */
export type ProjectionYear = {
    year: number;
    property_value: number;
    equity: number;
    cumulative_cash_flow: number;
    total_return: number;
    total_return_percent: number;
};

/**
 * Property goals and preferences from Step 1.
 */
export type PropertyGoals = {
    preferred_property_type?: (string | null);
    min_rooms?: (number | null);
    min_bathrooms?: (number | null);
    preferred_floor?: (string | null);
    has_elevator_required?: boolean;
    features?: Array<(string)>;
    min_size_sqm?: (number | null);
    max_size_sqm?: (number | null);
    additional_notes?: (string | null);
    is_completed?: boolean;
};

/**
 * Schema for updating property goals.
 */
export type PropertyGoalsUpdate = {
    preferred_property_type?: (string | null);
    min_rooms?: (number | null);
    min_bathrooms?: (number | null);
    preferred_floor?: (string | null);
    has_elevator_required?: (boolean | null);
    features?: (Array<(string)> | null);
    min_size_sqm?: (number | null);
    max_size_sqm?: (number | null);
    additional_notes?: (string | null);
    is_completed?: (boolean | null);
};

/**
 * Types of properties.
 */
export type PropertyType = 'apartment' | 'house' | 'land' | 'commercial';

/**
 * Property types a law applies to.
 */
export type PropertyTypeApplicability = 'all' | 'apartment' | 'house' | 'land' | 'commercial';

/**
 * Answers from the onboarding questionnaire.
 */
export type QuestionnaireAnswers = {
    property_type: PropertyType;
    property_location: string;
    financing_type: FinancingType;
    is_first_time_buyer?: boolean;
    has_german_residency?: boolean;
    budget_euros?: (number | null);
    target_purchase_date?: (string | null);
};

/**
 * Schema for token refresh request.
 */
export type RefreshTokenRequest = {
    refresh_token: string;
};

/**
 * Schema for user registration.
 *
 * Password requirements:
 * - Minimum 8 characters
 * - At least 1 uppercase letter
 * - At least 1 number
 */
export type RegisterRequest = {
    email: string;
    password: string;
    full_name?: (string | null);
    citizenship?: (string | null);
};

/**
 * Schema for registration response.
 */
export type RegisterResponse = {
    id: string;
    email: string;
    full_name?: (string | null);
    citizenship?: (string | null);
    email_verified?: boolean;
    created_at: string;
};

/**
 * Schema for resending verification email.
 */
export type ResendVerificationRequest = {
    email: string;
};

/**
 * Risk level for translated terms.
 */
export type RiskLevel = 'none' | 'low' | 'medium' | 'high';

/**
 * Request to create/calculate an ROI analysis.
 */
export type ROICalculationCreate = {
    name?: (string | null);
    /**
     * Property purchase price in EUR
     */
    purchase_price: number;
    /**
     * Down payment in EUR
     */
    down_payment: number;
    /**
     * Monthly rental income in EUR
     */
    monthly_rent: number;
    /**
     * Monthly operating expenses in EUR
     */
    monthly_expenses: number;
    /**
     * Expected annual appreciation %
     */
    annual_appreciation: number;
    /**
     * Expected vacancy rate %
     */
    vacancy_rate: number;
    /**
     * Annual mortgage interest rate %
     */
    mortgage_rate: number;
    /**
     * Mortgage term in years
     */
    mortgage_term: number;
};

/**
 * List of saved ROI calculations.
 */
export type ROICalculationListResponse = {
    data: Array<ROICalculationSummary>;
    count: number;
};

/**
 * Full response for a saved ROI calculation.
 */
export type ROICalculationResponse = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    purchase_price: number;
    down_payment: number;
    monthly_rent: number;
    monthly_expenses: number;
    annual_appreciation: number;
    vacancy_rate: number;
    mortgage_rate: number;
    mortgage_term: number;
    gross_rental_income: number;
    net_operating_income: number;
    annual_cash_flow: number;
    monthly_mortgage_payment: number;
    gross_yield: number;
    net_yield: number;
    cap_rate: number;
    cash_on_cash_return: number;
    investment_grade: number;
    investment_grade_label: string;
    projections: Array<ProjectionYear>;
    created_at: string;
};

/**
 * Summary for list views.
 */
export type ROICalculationSummary = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    purchase_price: number;
    investment_grade: number;
    investment_grade_label: string;
    annual_cash_flow: number;
    created_at: string;
};

/**
 * Request to compare multiple ROI scenarios.
 */
export type ROICompareRequest = {
    /**
     * 2-4 scenarios to compare
     */
    scenarios: Array<ROICalculationCreate>;
};

/**
 * Response for ROI scenario comparison.
 */
export type ROICompareResponse = {
    scenarios: Array<ROICompareResultItem>;
};

/**
 * Single scenario result in a comparison.
 */
export type ROICompareResultItem = {
    name?: (string | null);
    purchase_price: number;
    down_payment: number;
    monthly_rent: number;
    gross_rental_income: number;
    net_operating_income: number;
    annual_cash_flow: number;
    monthly_mortgage_payment: number;
    gross_yield: number;
    net_yield: number;
    cap_rate: number;
    cash_on_cash_return: number;
    investment_grade: number;
    investment_grade_label: string;
    projections: Array<ProjectionYear>;
};

/**
 * Brief calculation info for dashboard lists.
 */
export type SavedCalculationSummary = {
    id: string;
    name?: (string | null);
    calculator_type: string;
    headline_value: string;
    created_at: string;
};

/**
 * Brief document info for dashboard lists.
 */
export type SavedDocumentSummary = {
    id: string;
    original_filename: string;
    document_type: string;
    status: string;
    created_at: string;
};

/**
 * Cost breakdown for a single state in comparison view.
 */
export type StateComparisonItem = {
    state_code: string;
    state_name: string;
    transfer_tax_rate: number;
    transfer_tax: number;
    notary_fee: number;
    land_registry_fee: number;
    agent_commission: number;
    total_cost: number;
};

/**
 * Response for state-by-state comparison.
 */
export type StateComparisonResponse = {
    property_price: number;
    include_agent: boolean;
    data: Array<StateComparisonItem>;
};

/**
 * Transfer tax rate for a German state.
 */
export type StateRate = {
    state_code: string;
    state_name: string;
    transfer_tax_rate: number;
};

/**
 * Response containing all state rates and cost defaults.
 */
export type StateRatesResponse = {
    data: Array<StateRate>;
    cost_defaults: CostDefaults;
};

/**
 * Response schema for state variations.
 */
export type StateVariationResponse = {
    state_code: string;
    state_name: string;
    variation_title: string;
    variation_value?: (string | null);
    variation_description: string;
    effective_date?: (string | null);
    id: string;
};

/**
 * Status of a journey step.
 */
export type StepStatus = 'not_started' | 'in_progress' | 'completed' | 'skipped';

/**
 * Current subscription status.
 */
export type SubscriptionResponse = {
    tier: SubscriptionTier;
    stripe_customer_id?: (string | null);
    status?: (string | null);
};

/**
 * User subscription tier levels.
 */
export type SubscriptionTier = 'free' | 'premium' | 'enterprise';

/**
 * Supported languages for translation.
 */
export type SupportedLanguage = 'de' | 'en' | 'fr' | 'es' | 'it' | 'pl' | 'tr' | 'ru' | 'ar' | 'zh-Hans';

/**
 * Information about a supported language.
 */
export type SupportedLanguageInfo = {
    code: string;
    name: string;
};

/**
 * Response with list of supported languages.
 */
export type SupportedLanguagesResponse = {
    languages: Array<SupportedLanguageInfo>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * A single page of translated content.
 */
export type TranslatedPage = {
    page_number: number;
    original_text: string;
    translated_text: string;
};

/**
 * Request schema for text translation.
 */
export type TranslationRequest = {
    /**
     * Text to translate
     */
    text: string;
    /**
     * Source language code
     */
    source_language?: SupportedLanguage;
    /**
     * Target language code
     */
    target_language?: SupportedLanguage;
    /**
     * Include warnings for legal/financial terms
     */
    include_legal_warnings?: boolean;
};

/**
 * Response schema for text translation.
 */
export type TranslationResponse = {
    /**
     * Translation result
     */
    translation: TranslationResult;
    /**
     * Warnings about legal/financial terms
     */
    legal_warnings?: Array<LegalTermWarning>;
    /**
     * Whether the translation requires manual review
     */
    requires_review?: boolean;
    /**
     * Number of characters translated
     */
    character_count: number;
};

/**
 * Result of a single text translation.
 */
export type TranslationResult = {
    /**
     * Original text
     */
    original_text: string;
    /**
     * Translated text
     */
    translated_text: string;
    /**
     * Detected or specified source language
     */
    source_language: string;
    /**
     * Target language
     */
    target_language: string;
    /**
     * Confidence score of the translation (0-1)
     */
    confidence: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    citizenship?: (string | null);
    password: string;
};

/**
 * Schema for GDPR-compliant user data export.
 *
 * Contains all user data in a portable format as required by
 * GDPR Article 20 (Right to Data Portability).
 */
export type UserDataExport = {
    export_date: string;
    export_format_version?: string;
    id: string;
    email: string;
    full_name?: (string | null);
    citizenship?: (string | null);
    is_active: boolean;
    email_verified: boolean;
    subscription_tier: string;
    created_at: string;
    updated_at?: (string | null);
    items?: Array<ItemExport>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    citizenship?: (string | null);
    id: string;
    email_verified?: boolean;
    subscription_tier?: SubscriptionTier;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    citizenship?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Schema for email verification request.
 */
export type VerifyEmailRequest = {
    token: string;
};

/**
 * Schema for email verification response.
 */
export type VerifyEmailResponse = {
    message: string;
    email_verified: boolean;
};

/**
 * Webhook processing response.
 */
export type WebhookResponse = {
    received: boolean;
};

export type AuthRegisterData = {
    requestBody: RegisterRequest;
};

export type AuthRegisterResponse = (RegisterResponse);

export type AuthLoginData = {
    requestBody: LoginRequest;
};

export type AuthLoginResponse = (AuthToken);

export type AuthRefreshTokenData = {
    requestBody: RefreshTokenRequest;
};

export type AuthRefreshTokenResponse = (AuthToken);

export type AuthLogoutData = {
    requestBody: LogoutRequest;
};

export type AuthLogoutResponse = (void);

export type AuthVerifyEmailData = {
    requestBody: VerifyEmailRequest;
};

export type AuthVerifyEmailResponse = (VerifyEmailResponse);

export type AuthResendVerificationData = {
    requestBody: ResendVerificationRequest;
};

export type AuthResendVerificationResponse = (VerifyEmailResponse);

export type CalculatorsGetStateRatesResponse = (StateRatesResponse);

export type CalculatorsCompareStatesData = {
    /**
     * Include agent commission
     */
    includeAgent?: boolean;
    /**
     * Property price in EUR
     */
    price: number;
};

export type CalculatorsCompareStatesResponse = (StateComparisonResponse);

export type CalculatorsGetSharedCalculationData = {
    shareId: string;
};

export type CalculatorsGetSharedCalculationResponse = (HiddenCostCalculationResponse);

export type CalculatorsListCalculationsResponse = (HiddenCostCalculationListResponse);

export type CalculatorsSaveCalculationData = {
    requestBody: HiddenCostCalculationCreate;
};

export type CalculatorsSaveCalculationResponse = (HiddenCostCalculationResponse);

export type CalculatorsGetCalculationData = {
    calcId: string;
};

export type CalculatorsGetCalculationResponse = (HiddenCostCalculationResponse);

export type CalculatorsDeleteCalculationData = {
    calcId: string;
};

export type CalculatorsDeleteCalculationResponse = (void);

export type CalculatorsCompareRoiScenariosData = {
    requestBody: ROICompareRequest;
};

export type CalculatorsCompareRoiScenariosResponse = (ROICompareResponse);

export type CalculatorsGetSharedRoiCalculationData = {
    shareId: string;
};

export type CalculatorsGetSharedRoiCalculationResponse = (ROICalculationResponse);

export type CalculatorsListRoiCalculationsResponse = (ROICalculationListResponse);

export type CalculatorsSaveRoiCalculationData = {
    requestBody: ROICalculationCreate;
};

export type CalculatorsSaveRoiCalculationResponse = (ROICalculationResponse);

export type CalculatorsGetRoiCalculationData = {
    calcId: string;
};

export type CalculatorsGetRoiCalculationResponse = (ROICalculationResponse);

export type CalculatorsDeleteRoiCalculationData = {
    calcId: string;
};

export type CalculatorsDeleteRoiCalculationResponse = (void);

export type DashboardGetDashboardOverviewResponse = (DashboardOverviewResponse);

export type DocumentsUploadDocumentData = {
    formData: Body_documents_upload_document;
};

export type DocumentsUploadDocumentResponse = (DocumentUploadResponse);

export type DocumentsListDocumentsData = {
    page?: number;
    pageSize?: number;
};

export type DocumentsListDocumentsResponse = (DocumentListResponse);

export type DocumentsGetDocumentData = {
    documentId: string;
};

export type DocumentsGetDocumentResponse = (DocumentDetailResponse);

export type DocumentsGetDocumentTranslationData = {
    documentId: string;
};

export type DocumentsGetDocumentTranslationResponse = (DocumentTranslationResponse);

export type DocumentsGetDocumentStatusData = {
    documentId: string;
};

export type DocumentsGetDocumentStatusResponse = (DocumentStatusResponse);

export type FinancingGetSharedAssessmentData = {
    shareId: string;
};

export type FinancingGetSharedAssessmentResponse = (FinancingAssessmentResponse);

export type FinancingListAssessmentsResponse = (FinancingAssessmentListResponse);

export type FinancingSaveAssessmentData = {
    requestBody: FinancingAssessmentCreate;
};

export type FinancingSaveAssessmentResponse = (FinancingAssessmentResponse);

export type FinancingGetAssessmentData = {
    assessmentId: string;
};

export type FinancingGetAssessmentResponse = (FinancingAssessmentResponse);

export type FinancingDeleteAssessmentData = {
    assessmentId: string;
};

export type FinancingDeleteAssessmentResponse = (void);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JourneysCreateJourneyData = {
    requestBody: JourneyCreate;
};

export type JourneysCreateJourneyResponse = (JourneyResponse);

export type JourneysListJourneysData = {
    activeOnly?: boolean;
};

export type JourneysListJourneysResponse = (JourneysListResponse);

export type JourneysGetJourneyData = {
    journeyId: string;
};

export type JourneysGetJourneyResponse = (JourneyDetailResponse);

export type JourneysUpdateJourneyData = {
    journeyId: string;
    requestBody: JourneyUpdate;
};

export type JourneysUpdateJourneyResponse = (JourneyResponse);

export type JourneysDeleteJourneyData = {
    journeyId: string;
};

export type JourneysDeleteJourneyResponse = (Message);

export type JourneysGetJourneyProgressData = {
    journeyId: string;
};

export type JourneysGetJourneyProgressResponse = (JourneyProgressResponse);

export type JourneysGetNextStepData = {
    journeyId: string;
};

export type JourneysGetNextStepResponse = (NextStepResponse);

export type JourneysUpdateStepStatusData = {
    journeyId: string;
    requestBody: JourneyStepUpdate;
    stepId: string;
};

export type JourneysUpdateStepStatusResponse = (JourneyStepResponse);

export type JourneysUpdateTaskStatusData = {
    journeyId: string;
    requestBody: JourneyTaskUpdate;
    stepId: string;
    taskId: string;
};

export type JourneysUpdateTaskStatusResponse = (JourneyTaskResponse);

export type JourneysGetPropertyGoalsData = {
    journeyId: string;
};

export type JourneysGetPropertyGoalsResponse = (PropertyGoals);

export type JourneysUpdatePropertyGoalsData = {
    journeyId: string;
    requestBody: PropertyGoalsUpdate;
};

export type JourneysUpdatePropertyGoalsResponse = (PropertyGoals);

export type LawsListLawsData = {
    category?: (LawCategory | null);
    page?: number;
    pageSize?: number;
    propertyType?: (PropertyTypeApplicability | null);
    /**
     * German state code
     */
    state?: (string | null);
};

export type LawsListLawsResponse = (LawListResponse);

export type LawsSearchLawsData = {
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type LawsSearchLawsResponse = (LawSearchResponse);

export type LawsGetCategoriesResponse = ({
    [key: string]: unknown;
});

export type LawsGetLawsForJourneyStepData = {
    stepContentKey: string;
};

export type LawsGetLawsForJourneyStepResponse = (JourneyStepLawsResponse);

export type LawsGetBookmarksResponse = (BookmarkListResponse);

export type LawsGetLawData = {
    lawId: string;
};

export type LawsGetLawResponse = (LawDetailResponse);

export type LawsCreateBookmarkData = {
    lawId: string;
    requestBody: BookmarkCreate;
};

export type LawsCreateBookmarkResponse = (BookmarkResponse);

export type LawsDeleteBookmarkData = {
    lawId: string;
};

export type LawsDeleteBookmarkResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SubscriptionsGetCurrentSubscriptionResponse = (SubscriptionResponse);

export type SubscriptionsCreateCheckoutSessionData = {
    requestBody: CreateCheckoutRequest;
};

export type SubscriptionsCreateCheckoutSessionResponse = (CheckoutResponse);

export type SubscriptionsCreatePortalSessionData = {
    requestBody: PortalRequest;
};

export type SubscriptionsCreatePortalSessionResponse = (PortalResponse);

export type SubscriptionsHandleWebhookData = {
    stripeSignature: string;
};

export type SubscriptionsHandleWebhookResponse = (WebhookResponse);

export type SubscriptionsCancelSubscriptionResponse = (SubscriptionResponse);

export type TranslationsTranslateTextData = {
    requestBody: TranslationRequest;
};

export type TranslationsTranslateTextResponse = (TranslationResponse);

export type TranslationsDetectLanguageData = {
    requestBody: LanguageDetectionRequest;
};

export type TranslationsDetectLanguageResponse = (LanguageDetectionResponse);

export type TranslationsBatchTranslateData = {
    requestBody: BatchTranslationRequest;
};

export type TranslationsBatchTranslateResponse = (BatchTranslationResponse);

export type TranslationsGetSupportedLanguagesResponse = (SupportedLanguagesResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersExportUserDataResponse = (UserDataExport);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);