// This file is auto-generated by @hey-api/openapi-ts

/**
 * Single activity entry for the timeline.
 */
export type ActivityItem = {
    activity_type: ActivityType;
    title: string;
    description: string;
    entity_id: string;
    timestamp: string;
};

/**
 * Types of user activity tracked on the dashboard.
 */
export type ActivityType = 'journey_started' | 'step_completed' | 'document_uploaded' | 'calculation_saved' | 'roi_calculated' | 'financing_assessed' | 'law_bookmarked';

/**
 * AI-analyzed clause from a Kaufvertrag.
 */
export type AnalyzedClause = {
    section_name: string;
    section_name_en: string;
    original_text: string;
    plain_english_explanation: string;
    risk_level: 'low' | 'medium' | 'high';
    risk_reason: string;
    is_unusual?: boolean;
    unusual_terms?: Array<(string)>;
    page_number?: (number | null);
};

export type risk_level = 'low' | 'medium' | 'high';

export type AnnualCashflowRowResponse = {
    year?: number;
    cold_rent?: number;
    management_annual?: number;
    operational_cf?: number;
    loan_balance_start?: number;
    interest?: number;
    repayment?: number;
    loan_balance_end?: number;
    financing_cf?: number;
    net_cf_pretax?: number;
    renovation_deduction?: number;
    earnings_before_tax?: number;
    tax_effect_marginal?: number;
    net_cf_after_tax?: number;
    taxable_income_adjusted?: number;
    income_tax_adjusted?: number;
    actual_tax_saving?: number;
    property_value?: number;
    equity_buildup_accumulated?: number;
    equity_contribution?: number;
};

/**
 * Response for the area listing endpoint.
 */
export type AreaListResponse = {
    areas: Array<AreaSummary>;
};

/**
 * Summary of a comparable area (city or state).
 */
export type AreaSummary = {
    key: string;
    name: string;
    area_type: 'city' | 'state';
    state_code: string;
    state_name: string;
};

export type area_type = 'city' | 'state';

/**
 * Categories for content library articles.
 */
export type ArticleCategory = 'buying_process' | 'costs_and_taxes' | 'regulations' | 'common_pitfalls';

/**
 * Category with article count.
 */
export type ArticleCategoryInfo = {
    key: string;
    name: string;
    description: string;
    article_count: number;
};

/**
 * Request schema for creating an article.
 */
export type ArticleCreateRequest = {
    title: string;
    slug: string;
    meta_description: string;
    category: ArticleCategory;
    difficulty_level: DifficultyLevel;
    excerpt: string;
    content: string;
    key_takeaways?: Array<(string)>;
    author_name: string;
    related_law_ids?: Array<(string)>;
    related_calculator_types?: Array<(string)>;
    status?: ArticleStatus;
};

/**
 * Full detail response for an article.
 */
export type ArticleDetailResponse = {
    id: string;
    slug: string;
    title: string;
    meta_description: string;
    category: ArticleCategory;
    difficulty_level: DifficultyLevel;
    status: ArticleStatus;
    excerpt: string;
    content: string;
    key_takeaways?: Array<(string)>;
    reading_time_minutes: number;
    view_count: number;
    author_name: string;
    related_law_ids?: Array<(string)>;
    related_calculator_types?: Array<(string)>;
    created_at: string;
    updated_at: string;
    helpful_count?: number;
    not_helpful_count?: number;
    user_rating?: (boolean | null);
    related_articles?: Array<ArticleSummary>;
};

/**
 * Paginated list of articles.
 */
export type ArticleListResponse = {
    data: Array<ArticleSummary>;
    count: number;
    total: number;
    page: number;
    page_size: number;
};

/**
 * Request schema for rating an article.
 */
export type ArticleRatingRequest = {
    is_helpful: boolean;
};

/**
 * Response schema for article rating stats.
 */
export type ArticleRatingResponse = {
    helpful_count: number;
    not_helpful_count: number;
    user_rating?: (boolean | null);
};

/**
 * Search results response.
 */
export type ArticleSearchResponse = {
    data: Array<ArticleSearchResult>;
    count: number;
    query: string;
};

/**
 * Search result with relevance score.
 */
export type ArticleSearchResult = {
    id: string;
    slug: string;
    title: string;
    category: ArticleCategory;
    difficulty_level: DifficultyLevel;
    excerpt: string;
    reading_time_minutes: number;
    view_count: number;
    author_name: string;
    created_at: string;
    relevance_score: number;
};

/**
 * Publication status for articles.
 */
export type ArticleStatus = 'draft' | 'published' | 'archived';

/**
 * Summary view of an article for list responses.
 */
export type ArticleSummary = {
    id: string;
    slug: string;
    title: string;
    category: ArticleCategory;
    difficulty_level: DifficultyLevel;
    excerpt: string;
    reading_time_minutes: number;
    view_count: number;
    author_name: string;
    created_at: string;
};

/**
 * Request schema for updating an article. All fields optional.
 */
export type ArticleUpdateRequest = {
    title?: (string | null);
    slug?: (string | null);
    meta_description?: (string | null);
    category?: (ArticleCategory | null);
    difficulty_level?: (DifficultyLevel | null);
    excerpt?: (string | null);
    content?: (string | null);
    key_takeaways?: (Array<(string)> | null);
    author_name?: (string | null);
    related_law_ids?: (Array<(string)> | null);
    related_calculator_types?: (Array<(string)> | null);
    status?: (ArticleStatus | null);
};

/**
 * JWT token response with access and refresh tokens.
 */
export type AuthToken = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
};

/**
 * Request schema for batch text translation.
 */
export type BatchTranslationRequest = {
    /**
     * List of texts to translate
     */
    texts: Array<(string)>;
    /**
     * Source language code
     */
    source_language?: SupportedLanguage;
    /**
     * Target language code
     */
    target_language?: SupportedLanguage;
    /**
     * Include warnings for legal/financial terms
     */
    include_legal_warnings?: boolean;
};

/**
 * Response schema for batch text translation.
 */
export type BatchTranslationResponse = {
    /**
     * List of translation results
     */
    translations: Array<TranslationResponse>;
    /**
     * Total characters translated
     */
    total_character_count: number;
    /**
     * Total number of legal warnings
     */
    total_warnings: number;
};

export type Body_documents_upload_document = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_users_upload_avatar = {
    file: (Blob | File);
};

/**
 * Request schema for creating a bookmark.
 */
export type BookmarkCreate = {
    notes?: (string | null);
};

/**
 * Brief bookmarked law info for dashboard lists.
 */
export type BookmarkedLawSummary = {
    id: string;
    citation: string;
    title_en: string;
    category: string;
    bookmarked_at: string;
};

/**
 * List of user bookmarks.
 */
export type BookmarkListResponse = {
    data: Array<BookmarkResponse>;
    count: number;
};

/**
 * Response schema for a bookmark.
 */
export type BookmarkResponse = {
    id: string;
    law_id: string;
    notes?: (string | null);
    created_at: string;
    law: LawSummary;
};

/**
 * Response with checkout session details.
 */
export type CheckoutResponse = {
    session_id: string;
    url: string;
};

/**
 * Full comparison metrics for a single area.
 */
export type ComparisonMetrics = {
    key: string;
    name: string;
    area_type: 'city' | 'state';
    state_code: string;
    state_name: string;
    avg_price_per_sqm: number;
    price_range_min: number;
    price_range_max: number;
    avg_rent_per_sqm?: (number | null);
    rent_range_min?: (number | null);
    rent_range_max?: (number | null);
    gross_rental_yield?: (number | null);
    transfer_tax_rate: number;
    agent_fee_percent?: (number | null);
    trend?: ('rising' | 'stable' | 'falling' | null);
    has_mietspiegel: boolean;
};

/**
 * Response for the area comparison endpoint.
 */
export type ComparisonResponse = {
    areas: Array<ComparisonMetrics>;
};

/**
 * Fine-grained Nebenkosten (running cost) categories.
 */
export type CostCategory = 'hausgeld' | 'grundsteuer' | 'insurance' | 'heating' | 'water' | 'electricity' | 'maintenance' | 'misc';

/**
 * Summary for a single Nebenkosten category.
 */
export type CostCategorySummary = {
    category: string;
    actual_total: number;
    estimated_total: (number | null);
    variance: (number | null);
    variance_percent: (number | null);
    is_over_threshold: boolean;
};

/**
 * Default cost percentages used in calculations.
 */
export type CostDefaults = {
    notary_fee_percent: number;
    land_registry_fee_percent: number;
    agent_commission_percent: number;
};

/**
 * Aggregated running-cost summary across all Nebenkosten categories.
 */
export type CostSummaryResponse = {
    categories: Array<CostCategorySummary>;
    total_actual: number;
    total_estimated: (number | null);
    total_variance: (number | null);
    highest_category: (string | null);
    alert_categories: Array<(string)>;
};

/**
 * Response schema for court rulings.
 */
export type CourtRulingResponse = {
    court_name: string;
    case_number: string;
    ruling_date: string;
    title: string;
    summary: string;
    significance?: (string | null);
    source_url?: (string | null);
    id: string;
};

/**
 * Request to create a checkout session.
 */
export type CreateCheckoutRequest = {
    tier: SubscriptionTier;
    success_url: string;
    cancel_url: string;
};

/**
 * Aggregated dashboard data for the authenticated user.
 */
export type DashboardOverviewResponse = {
    journey?: (JourneyOverview | null);
    has_journey: boolean;
    recent_documents: Array<SavedDocumentSummary>;
    recent_calculations: Array<SavedCalculationSummary>;
    bookmarked_laws: Array<BookmarkedLawSummary>;
    recent_activity: Array<ActivityItem>;
    documents_translated_this_month: number;
    total_calculations: number;
    total_bookmarks: number;
};

/**
 * A legal clause detected in the document.
 */
export type DetectedClause = {
    /**
     * Type: purchase_price, deadline, warranty_exclusion, special_condition, financial_term
     */
    clause_type: string;
    original_text: string;
    translated_text: string;
    page_number: number;
    /**
     * Risk level: low, medium, high
     */
    risk_level: string;
};

/**
 * Difficulty level for articles.
 */
export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced';

/**
 * Full document detail with optional translation.
 */
export type DocumentDetailResponse = {
    id: string;
    original_filename: string;
    file_size_bytes: number;
    page_count: number;
    document_type: DocumentTypeEnum;
    status: DocumentStatusEnum;
    error_message?: (string | null);
    share_id?: (string | null);
    journey_step_id?: (string | null);
    created_at: string;
    translation?: (DocumentTranslationResponse | null);
};

/**
 * Paginated list of documents.
 */
export type DocumentListResponse = {
    data: Array<DocumentSummary>;
    total: number;
    page: number;
    page_size: number;
};

/**
 * Risk warning for a term in the document.
 */
export type DocumentRiskWarning = {
    original_term: string;
    translated_term: string;
    risk_level: string;
    explanation: string;
    page_number?: (number | null);
};

/**
 * Response after generating a share link for a document.
 */
export type DocumentShareResponse = {
    id: string;
    share_id: string;
};

/**
 * Processing status for uploaded documents.
 */
export type DocumentStatus = 'uploaded' | 'processing' | 'completed' | 'failed';

/**
 * Document processing status choices.
 */
export type DocumentStatusEnum = 'uploaded' | 'processing' | 'completed' | 'failed';

/**
 * Lightweight status check response.
 */
export type DocumentStatusResponse = {
    id: string;
    status: DocumentStatusEnum;
    error_message?: (string | null);
    page_count: number;
};

/**
 * Summary of a document for list views.
 */
export type DocumentSummary = {
    id: string;
    original_filename: string;
    file_size_bytes: number;
    page_count: number;
    document_type: DocumentTypeEnum;
    status: DocumentStatusEnum;
    share_id?: (string | null);
    journey_step_id?: (string | null);
    created_at: string;
};

/**
 * Full translation result for a document.
 */
export type DocumentTranslationResponse = {
    id: string;
    document_id: string;
    source_language: string;
    target_language: string;
    translated_pages: Array<TranslatedPage>;
    clauses_detected: Array<DetectedClause>;
    risk_warnings: Array<DocumentRiskWarning>;
    kaufvertrag_analysis?: (KaufvertragAnalysis | null);
    processing_started_at?: (string | null);
    processing_completed_at?: (string | null);
};

/**
 * Types of German real estate documents.
 */
export type DocumentType = 'kaufvertrag' | 'mietvertrag' | 'expose' | 'nebenkostenabrechnung' | 'grundbuchauszug' | 'teilungserklaerung' | 'hausgeldabrechnung' | 'unknown';

/**
 * Document type choices.
 */
export type DocumentTypeEnum = 'kaufvertrag' | 'mietvertrag' | 'expose' | 'nebenkostenabrechnung' | 'grundbuchauszug' | 'teilungserklaerung' | 'hausgeldabrechnung' | 'unknown';

/**
 * Response after uploading a document.
 */
export type DocumentUploadResponse = {
    id: string;
    original_filename: string;
    file_size_bytes: number;
    page_count: number;
    document_type: DocumentTypeEnum;
    status: DocumentStatusEnum;
    journey_step_id?: (string | null);
};

/**
 * Document usage limits for the current user.
 */
export type DocumentUsageResponse = {
    documents_used: number;
    page_limit: number;
    subscription_tier: string;
};

/**
 * Schema for creating feedback.
 */
export type FeedbackCreate = {
    /**
     * Feedback category
     */
    category: string;
    message: string;
    page_url?: (string | null);
};

/**
 * Schema for feedback response.
 */
export type FeedbackResponse = {
    id: string;
    category: string;
    message: string;
    page_url: (string | null);
    created_at: string;
};

/**
 * Request to create a financing eligibility assessment.
 */
export type FinancingAssessmentCreate = {
    name?: (string | null);
    /**
     * Current employment type
     */
    employment_status: 'permanent' | 'fixed_term' | 'self_employed' | 'freelance' | 'civil_servant';
    /**
     * Years in current employment
     */
    employment_years: number;
    /**
     * Monthly net income in EUR
     */
    monthly_net_income: number;
    /**
     * Monthly debt obligations in EUR
     */
    monthly_debt: number;
    /**
     * Available down payment in EUR
     */
    available_down_payment: number;
    /**
     * SCHUFA NextGen Score rating category
     */
    schufa_rating: 'excellent' | 'good' | 'acceptable' | 'sufficient' | 'insufficient' | 'unknown';
    /**
     * Residency or citizenship status
     */
    residency_status: 'german_citizen' | 'eu_citizen' | 'permanent_resident' | 'temporary_resident' | 'non_eu' | 'non_resident';
};

/**
 * Current employment type
 */
export type employment_status = 'permanent' | 'fixed_term' | 'self_employed' | 'freelance' | 'civil_servant';

/**
 * SCHUFA NextGen Score rating category
 */
export type schufa_rating = 'excellent' | 'good' | 'acceptable' | 'sufficient' | 'insufficient' | 'unknown';

/**
 * Residency or citizenship status
 */
export type residency_status = 'german_citizen' | 'eu_citizen' | 'permanent_resident' | 'temporary_resident' | 'non_eu' | 'non_resident';

/**
 * List of saved financing assessments.
 */
export type FinancingAssessmentListResponse = {
    data: Array<FinancingAssessmentSummary>;
    count: number;
};

/**
 * Full response for a saved financing assessment.
 */
export type FinancingAssessmentResponse = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    employment_status: string;
    employment_years: number;
    monthly_net_income: number;
    monthly_debt: number;
    available_down_payment: number;
    schufa_rating: string;
    residency_status: string;
    employment_score: number;
    income_ratio_score: number;
    down_payment_score: number;
    schufa_score: number;
    residency_score: number;
    years_bonus_score: number;
    total_score: number;
    likelihood_label: string;
    max_loan_estimate: number;
    recommended_down_payment_percent: number;
    expected_rate_min: number;
    expected_rate_max: number;
    ltv_ratio: number;
    strengths: Array<(string)>;
    improvements: Array<(string)>;
    document_checklist: Array<(string)>;
    created_at: string;
};

/**
 * Summary for list views.
 */
export type FinancingAssessmentSummary = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    total_score: number;
    likelihood_label: string;
    max_loan_estimate: number;
    created_at: string;
};

/**
 * Types of financing.
 */
export type FinancingType = 'cash' | 'mortgage' | 'mixed';

/**
 * Schema for forgot password request.
 */
export type ForgotPasswordRequest = {
    email: string;
};

/**
 * Schema for forgot password response.
 */
export type ForgotPasswordResponse = {
    message: string;
};

/**
 * Response for global search across laws and articles.
 */
export type GlobalSearchResponse = {
    query: string;
    laws: Array<SearchResultItem>;
    articles: Array<SearchResultItem>;
    total_count: number;
};

/**
 * List of categories with counts.
 */
export type GlossaryCategoriesResponse = {
    categories: Array<GlossaryCategoryInfo>;
};

/**
 * Categories for German real estate glossary terms.
 */
export type GlossaryCategory = 'buying_process' | 'costs_taxes' | 'financing' | 'legal' | 'rental' | 'property_types';

/**
 * Category with term count.
 */
export type GlossaryCategoryInfo = {
    id: string;
    name: string;
    count: number;
};

/**
 * Paginated list of glossary terms.
 */
export type GlossaryListResponse = {
    data: Array<GlossaryTermSummary>;
    total: number;
    page: number;
    page_size: number;
};

/**
 * Search results response.
 */
export type GlossarySearchResponse = {
    query: string;
    results: Array<GlossaryTermSummary>;
    total: number;
};

/**
 * Full detail view of a glossary term.
 */
export type GlossaryTermDetail = {
    id: string;
    term_de: string;
    term_en: string;
    slug: string;
    definition_short: string;
    category: GlossaryCategory;
    definition_long: string;
    example_usage?: (string | null);
    related_terms?: Array<GlossaryTermSummary>;
};

/**
 * Summary view of a glossary term for list responses.
 */
export type GlossaryTermSummary = {
    id: string;
    term_de: string;
    term_en: string;
    slug: string;
    definition_short: string;
    category: GlossaryCategory;
};

/**
 * Request to save a hidden cost calculation.
 */
export type HiddenCostCalculationCreate = {
    name?: (string | null);
    /**
     * Property price in EUR
     */
    property_price: number;
    /**
     * German state code
     */
    state_code: string;
    property_type: string;
    include_agent?: boolean;
    renovation_level?: 'none' | 'light' | 'medium' | 'full';
    include_moving?: boolean;
};

export type renovation_level = 'none' | 'light' | 'medium' | 'full';

/**
 * Paginated list of saved calculations.
 */
export type HiddenCostCalculationListResponse = {
    data: Array<HiddenCostCalculationSummary>;
    count: number;
};

/**
 * Full response for a saved calculation.
 */
export type HiddenCostCalculationResponse = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    property_price: number;
    state_code: string;
    property_type: string;
    include_agent: boolean;
    renovation_level: string;
    include_moving: boolean;
    transfer_tax: number;
    notary_fee: number;
    land_registry_fee: number;
    agent_commission: number;
    renovation_estimate: number;
    moving_costs: number;
    total_additional_costs: number;
    total_cost_of_ownership: number;
    additional_cost_percentage: number;
    created_at: string;
};

/**
 * Summary for list views.
 */
export type HiddenCostCalculationSummary = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    property_price: number;
    state_code: string;
    total_additional_costs: number;
    total_cost_of_ownership: number;
    created_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Schema for creating a journey from questionnaire.
 */
export type JourneyCreate = {
    title?: string;
    questionnaire: QuestionnaireAnswers;
};

/**
 * Detailed journey response with full step data.
 */
export type JourneyDetailResponse = {
    id: string;
    title: string;
    current_phase: JourneyPhase;
    current_step_number: number;
    property_type?: (PropertyType | null);
    property_location?: (string | null);
    financing_type?: (FinancingType | null);
    is_first_time_buyer: boolean;
    has_german_residency: boolean;
    budget_euros?: (number | null);
    target_purchase_date?: (string | null);
    property_use?: (string | null);
    property_goals?: (PropertyGoals | null);
    market_insights?: (MarketInsightsData | null);
    started_at?: (string | null);
    completed_at?: (string | null);
    is_active: boolean;
    created_at: string;
    steps?: Array<JourneyStepResponse>;
    progress_percentage?: number;
    completed_steps?: number;
    total_steps?: number;
};

/**
 * Summary of user's active journey for dashboard display.
 */
export type JourneyOverview = {
    id: string;
    title: string;
    current_phase: string;
    current_step_number: number;
    progress_percentage: number;
    completed_steps: number;
    total_steps: number;
    estimated_days_remaining?: (number | null);
    started_at?: (string | null);
    next_step_title?: (string | null);
    next_step_id?: (string | null);
    phases: {
        [key: string]: {
            [key: string]: (number);
        };
    };
    budget_euros?: (number | null);
    target_purchase_date?: (string | null);
    days_to_target?: (number | null);
    estimated_total_cost?: (number | null);
};

/**
 * Phases of the property buying journey.
 */
export type JourneyPhase = 'research' | 'preparation' | 'buying' | 'closing' | 'ownership' | 'rental_setup';

/**
 * Schema for journey progress.
 */
export type JourneyProgressResponse = {
    journey_id: string;
    total_steps: number;
    completed_steps: number;
    current_step_number: number;
    current_phase: JourneyPhase;
    progress_percentage: number;
    estimated_days_remaining?: (number | null);
    phases: {
        [key: string]: {
            [key: string]: (number);
        };
    };
};

/**
 * Schema for journey response.
 */
export type JourneyResponse = {
    id: string;
    title: string;
    current_phase: JourneyPhase;
    current_step_number: number;
    property_type?: (PropertyType | null);
    property_location?: (string | null);
    financing_type?: (FinancingType | null);
    is_first_time_buyer: boolean;
    has_german_residency: boolean;
    budget_euros?: (number | null);
    target_purchase_date?: (string | null);
    property_use?: (string | null);
    property_goals?: (PropertyGoals | null);
    market_insights?: (MarketInsightsData | null);
    started_at?: (string | null);
    completed_at?: (string | null);
    is_active: boolean;
    created_at: string;
    steps?: Array<JourneyStepSummary>;
    progress_percentage?: number;
    completed_steps?: number;
    total_steps?: number;
};

/**
 * Schema for list of journeys.
 */
export type JourneysListResponse = {
    data: Array<JourneyResponse>;
    count: number;
};

/**
 * Response for laws linked to a journey step.
 */
export type JourneyStepLawResponse = {
    law: LawSummary;
    relevance_score: number;
};

/**
 * List of laws for a journey step.
 */
export type JourneyStepLawsResponse = {
    data: Array<JourneyStepLawResponse>;
    count: number;
    step_content_key: string;
};

/**
 * Schema for journey step response.
 */
export type JourneyStepResponse = {
    step_number: number;
    phase: JourneyPhase;
    title: string;
    description?: (string | null);
    estimated_duration_days?: (number | null);
    id: string;
    status: StepStatus;
    started_at?: (string | null);
    completed_at?: (string | null);
    content_key?: (string | null);
    related_laws?: (Array<(string)> | null);
    estimated_costs?: ({
    [key: string]: unknown;
} | null);
    tasks?: Array<JourneyTaskResponse>;
};

/**
 * Summary schema for journey step (without tasks).
 */
export type JourneyStepSummary = {
    id: string;
    step_number: number;
    phase: JourneyPhase;
    title: string;
    status: StepStatus;
    estimated_duration_days?: (number | null);
};

/**
 * Schema for updating a journey step status.
 */
export type JourneyStepUpdate = {
    status: StepStatus;
};

/**
 * Schema for journey task response.
 */
export type JourneyTaskResponse = {
    title: string;
    description?: (string | null);
    is_required?: boolean;
    resource_url?: (string | null);
    resource_type?: (string | null);
    id: string;
    order: number;
    is_completed: boolean;
    completed_at?: (string | null);
};

/**
 * Schema for updating a journey task.
 */
export type JourneyTaskUpdate = {
    is_completed: boolean;
};

/**
 * Schema for updating journey metadata.
 */
export type JourneyUpdate = {
    title?: (string | null);
    target_purchase_date?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Full AI analysis of a Kaufvertrag (purchase contract).
 */
export type KaufvertragAnalysis = {
    summary: string;
    analyzed_clauses: Array<AnalyzedClause>;
    notary_checklist: Array<NotaryQuestion>;
    overall_risk_assessment: 'low' | 'medium' | 'high';
    overall_risk_explanation: string;
    is_ai_generated?: boolean;
};

export type overall_risk_assessment = 'low' | 'medium' | 'high';

/**
 * Request schema for language detection.
 */
export type LanguageDetectionRequest = {
    /**
     * Text to detect language of
     */
    text: string;
};

/**
 * Response schema for language detection.
 */
export type LanguageDetectionResponse = {
    /**
     * Detected language code
     */
    language: string;
    /**
     * Confidence score of detection (0-1)
     */
    confidence: number;
    /**
     * Whether the detected language is supported for translation
     */
    is_supported: boolean;
};

/**
 * Categories for German real estate laws.
 */
export type LawCategory = 'buying_process' | 'costs_and_taxes' | 'rental_law' | 'condominium' | 'agent_regulations';

/**
 * Extended response with related laws.
 */
export type LawDetailResponse = {
    id: string;
    citation: string;
    title_de: string;
    title_en: string;
    category: LawCategory;
    property_type: PropertyTypeApplicability;
    one_line_summary: string;
    short_summary: string;
    detailed_explanation: string;
    real_world_example?: (string | null);
    common_disputes?: (string | null);
    buyer_implications?: (string | null);
    seller_implications?: (string | null);
    landlord_implications?: (string | null);
    tenant_implications?: (string | null);
    original_text_de?: (string | null);
    last_amended?: (string | null);
    change_history?: (string | null);
    created_at: string;
    updated_at: string;
    court_rulings?: Array<CourtRulingResponse>;
    state_variations?: Array<StateVariationResponse>;
    related_laws?: Array<LawSummary>;
    is_bookmarked?: boolean;
};

/**
 * Paginated list of laws.
 */
export type LawListResponse = {
    data: Array<LawSummary>;
    count: number;
    total: number;
    page: number;
    page_size: number;
};

/**
 * Search results response.
 */
export type LawSearchResponse = {
    data: Array<LawSearchResult>;
    count: number;
    query: string;
};

/**
 * Search result with relevance score.
 */
export type LawSearchResult = {
    id: string;
    citation: string;
    title_en: string;
    category: LawCategory;
    property_type: PropertyTypeApplicability;
    one_line_summary: string;
    relevance_score: number;
    matched_fields?: Array<(string)>;
};

/**
 * Summary view of a law for list responses.
 */
export type LawSummary = {
    id: string;
    citation: string;
    title_en: string;
    category: LawCategory;
    property_type: PropertyTypeApplicability;
    one_line_summary: string;
};

/**
 * Warning about a legal or financial term in translation.
 */
export type LegalTermWarning = {
    /**
     * Original term in source language
     */
    original_term: string;
    /**
     * Translated term
     */
    translated_term: string;
    /**
     * Risk level for this term
     */
    risk_level: RiskLevel;
    /**
     * Explanation of why this term requires attention
     */
    explanation: string;
};

/**
 * Schema for login request.
 */
export type LoginRequest = {
    email: string;
    password: string;
    remember_me?: boolean;
};

/**
 * Schema for logout request.
 */
export type LogoutRequest = {
    refresh_token: string;
};

/**
 * Computed market insights stored on the journey after Step 1 completion.
 */
export type MarketInsightsData = {
    state_code: string;
    state_name: string;
    avg_price_per_sqm: number;
    price_range_min: number;
    price_range_max: number;
    agent_fee_percent: number;
    trend: 'rising' | 'stable' | 'falling';
    hotspots: Array<(string)>;
    transfer_tax_rate: number;
    property_type: string;
    type_multiplier: number;
    adjusted_avg_price_per_sqm: number;
    adjusted_min_price_per_sqm: number;
    adjusted_max_price_per_sqm: number;
    estimated_size_sqm?: (number | null);
    preferred_area?: (string | null);
    generated_at: string;
};

export type trend = 'rising' | 'stable' | 'falling';

export type Message = {
    message: string;
};

/**
 * Single month in the portfolio performance time series.
 */
export type MonthlyPerformanceItem = {
    month: string;
    income: number;
    expenses: number;
    net_cash_flow: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Schema for next recommended step.
 */
export type NextStepResponse = {
    has_next: boolean;
    step?: (JourneyStepResponse | null);
    message?: (string | null);
};

/**
 * Question to ask a notary about a contract clause.
 */
export type NotaryQuestion = {
    question: string;
    related_clause: string;
    priority: 'essential' | 'recommended' | 'optional';
};

export type priority = 'essential' | 'recommended' | 'optional';

/**
 * Paginated list of notifications.
 */
export type NotificationListResponse = {
    data: Array<NotificationResponse>;
    count: number;
    unread_count: number;
};

/**
 * Single notification preference.
 */
export type NotificationPreferenceItem = {
    notification_type: NotificationType;
    is_in_app_enabled?: boolean;
    is_email_enabled?: boolean;
};

/**
 * Full notification preferences response.
 */
export type NotificationPreferencesResponse = {
    preferences: Array<NotificationPreferenceItem>;
};

/**
 * Request body to update notification preferences.
 */
export type NotificationPreferencesUpdate = {
    preferences: Array<NotificationPreferenceItem>;
};

/**
 * Single notification response.
 */
export type NotificationResponse = {
    id: string;
    type: NotificationType;
    title: string;
    message: string;
    is_read: boolean;
    action_url?: (string | null);
    created_at: string;
};

/**
 * Types of notifications.
 */
export type NotificationType = 'step_completed' | 'document_translated' | 'calculation_saved' | 'law_bookmarked' | 'journey_deadline' | 'payment_reminder' | 'subscription_expiring' | 'system_announcement' | 'weekly_digest';

/**
 * List of saved ownership comparisons.
 */
export type OwnershipComparisonListResponse = {
    data: Array<OwnershipComparisonSummary>;
    count: number;
};

/**
 * Request to calculate or save a GmbH vs. private ownership comparison.
 */
export type OwnershipComparisonRequest = {
    name?: (string | null);
    num_properties: number;
    annual_rental_income: number;
    personal_marginal_tax_rate: number;
    annual_appreciation: number;
    holding_period: number;
    total_property_value: number;
    building_share_percent?: number;
    afa_rate_percent?: number;
    annual_rent_increase_percent?: number;
    gewerbesteuer_hebesatz?: number;
    gmbh_setup_cost?: number;
    annual_accounting_cost?: number;
};

/**
 * Pure calculation result for GmbH vs. private comparison.
 */
export type OwnershipComparisonResponse = {
    private: ScenarioResult;
    gmbh: ScenarioResult;
    breakeven_year: (number | null);
    gmbh_advantage_at_exit: number;
    recommendation: string;
};

/**
 * Response for a saved ownership comparison with DB fields.
 */
export type OwnershipComparisonSavedResponse = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    num_properties: number;
    annual_rental_income: number;
    personal_marginal_tax_rate: number;
    annual_appreciation: number;
    holding_period: number;
    total_property_value: number;
    building_share_percent: number;
    afa_rate_percent: number;
    annual_rent_increase_percent: number;
    gewerbesteuer_hebesatz: number;
    gmbh_setup_cost: number;
    annual_accounting_cost: number;
    private_total_wealth: number;
    gmbh_total_wealth: number;
    breakeven_year: (number | null);
    gmbh_advantage_at_exit: number;
    recommendation: string;
    results: {
        [key: string]: unknown;
    };
    created_at: string;
};

/**
 * Summary for list views.
 */
export type OwnershipComparisonSummary = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    num_properties: number;
    total_property_value: number;
    private_total_wealth: number;
    gmbh_total_wealth: number;
    recommendation: string;
    created_at: string;
};

export type PasswordRecoveryRequest = {
    email: string;
};

/**
 * Request to create a customer portal session.
 */
export type PortalRequest = {
    return_url: string;
};

/**
 * Response with portal session URL.
 */
export type PortalResponse = {
    url: string;
};

/**
 * Monthly portfolio performance for the trailing 12 months.
 */
export type PortfolioPerformanceResponse = {
    months: Array<MonthlyPerformanceItem>;
    has_data: boolean;
};

/**
 * Request to create a portfolio property.
 */
export type PortfolioPropertyCreate = {
    address: string;
    city: string;
    postcode: string;
    state_code?: (string | null);
    purchase_price: number;
    purchase_date?: (string | null);
    square_meters: number;
    building_year?: (number | null);
    current_value_estimate?: (number | null);
    monthly_rent_target?: (number | null);
    tenant_name?: (string | null);
    lease_start_date?: (string | null);
    lease_end_date?: (string | null);
    monthly_hausgeld?: (number | null);
    is_vacant?: boolean;
    notes?: (string | null);
    journey_id?: (string | null);
};

/**
 * Paginated list of portfolio properties.
 */
export type PortfolioPropertyListResponse = {
    data: Array<PortfolioPropertySummary>;
    count: number;
};

/**
 * Full response for a portfolio property.
 */
export type PortfolioPropertyResponse = {
    id: string;
    address: string;
    city: string;
    postcode: string;
    state_code?: (string | null);
    purchase_price: number;
    purchase_date?: (string | null);
    square_meters: number;
    building_year?: (number | null);
    current_value_estimate?: (number | null);
    monthly_rent_target?: (number | null);
    tenant_name?: (string | null);
    lease_start_date?: (string | null);
    lease_end_date?: (string | null);
    monthly_hausgeld?: (number | null);
    is_vacant: boolean;
    notes?: (string | null);
    journey_id?: (string | null);
    created_at: string;
};

/**
 * Lighter property summary for list views.
 */
export type PortfolioPropertySummary = {
    id: string;
    address: string;
    city: string;
    postcode: string;
    purchase_price: number;
    monthly_rent_target?: (number | null);
    is_vacant: boolean;
    created_at: string;
};

/**
 * Request to partially update a portfolio property.
 */
export type PortfolioPropertyUpdate = {
    address?: (string | null);
    city?: (string | null);
    postcode?: (string | null);
    state_code?: (string | null);
    purchase_price?: (number | null);
    purchase_date?: (string | null);
    square_meters?: (number | null);
    building_year?: (number | null);
    current_value_estimate?: (number | null);
    monthly_rent_target?: (number | null);
    tenant_name?: (string | null);
    lease_start_date?: (string | null);
    lease_end_date?: (string | null);
    monthly_hausgeld?: (number | null);
    is_vacant?: (boolean | null);
    notes?: (string | null);
};

/**
 * Aggregated KPIs across the entire portfolio.
 */
export type PortfolioSummaryResponse = {
    total_properties: number;
    total_purchase_value: number;
    total_current_value: number;
    total_income: number;
    total_expenses: number;
    net_cash_flow: number;
    vacancy_rate: number;
    average_gross_yield: number;
};

/**
 * Request to create a portfolio transaction.
 */
export type PortfolioTransactionCreate = {
    /**
     * Transaction type enum value
     */
    type: TransactionType;
    amount: number;
    date: string;
    category?: (string | null);
    description?: (string | null);
    is_recurring?: boolean;
    cost_category?: (CostCategory | null);
    estimated_amount?: (number | null);
};

/**
 * List of portfolio transactions.
 */
export type PortfolioTransactionListResponse = {
    data: Array<PortfolioTransactionResponse>;
    count: number;
};

/**
 * Full response for a portfolio transaction.
 */
export type PortfolioTransactionResponse = {
    id: string;
    property_id: string;
    type: string;
    amount: number;
    date: string;
    category?: (string | null);
    description?: (string | null);
    is_recurring: boolean;
    cost_category?: (string | null);
    estimated_amount?: (number | null);
    created_at: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Professional detail with reviews.
 */
export type ProfessionalDetailResponse = {
    id: string;
    name: string;
    type: ProfessionalType;
    city: string;
    languages: string;
    description?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    is_verified: boolean;
    average_rating: number;
    review_count: number;
    recommendation_rate?: (number | null);
    review_highlights?: ({
    [key: string]: unknown;
} | null);
    created_at: string;
    reviews?: Array<ReviewResponse>;
};

/**
 * Paginated list of professionals.
 */
export type ProfessionalListResponse = {
    data: Array<ProfessionalResponse>;
    count: number;
    total: number;
    page: number;
    page_size: number;
};

/**
 * Professional summary for list and detail views.
 */
export type ProfessionalResponse = {
    id: string;
    name: string;
    type: ProfessionalType;
    city: string;
    languages: string;
    description?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    is_verified: boolean;
    average_rating: number;
    review_count: number;
    recommendation_rate?: (number | null);
    review_highlights?: ({
    [key: string]: unknown;
} | null);
    created_at: string;
};

/**
 * Types of professionals in the directory.
 */
export type ProfessionalType = 'lawyer' | 'notary' | 'tax_advisor' | 'mortgage_broker' | 'real_estate_agent';

/**
 * Single year projection data.
 */
export type ProjectionYear = {
    year: number;
    property_value: number;
    equity: number;
    cumulative_cash_flow: number;
    total_return: number;
    total_return_percent: number;
};

/**
 * Flat request model for the /calculate endpoint.
 *
 * All percent-scale values (e.g. broker_fee_percent=3.57 means 3.57%).
 * Every field has a default so the frontend only sends what it has.
 */
export type PropertyEvaluationCalculateRequest = {
    address?: string;
    square_meters?: number;
    purchase_price?: number;
    rent_per_m2?: number;
    parking_space_rent?: number;
    broker_fee_percent?: number;
    notary_fee_percent?: number;
    land_registry_fee_percent?: number;
    property_transfer_tax_percent?: number;
    base_allocable_costs?: number;
    property_tax_monthly?: number;
    base_non_allocable_costs?: number;
    reserves_monthly?: number;
    building_share_percent?: number;
    afa_rate_percent?: number;
    loan_percent?: number;
    interest_rate_percent?: number;
    initial_repayment_rate_percent?: number;
    personal_taxable_income?: number;
    marginal_tax_rate_percent?: number;
    cost_increase_percent?: number;
    rent_increase_percent?: number;
    value_increase_percent?: number;
    equity_interest_percent?: number;
    renovation_year?: number;
    renovation_cost?: number;
    start_year?: number;
    analysis_years?: number;
};

export type PropertyEvaluationCalculateResponse = {
    price_per_m2?: number;
    broker_fee_amount?: number;
    notary_fee_amount?: number;
    land_registry_fee_amount?: number;
    property_transfer_tax_amount?: number;
    total_closing_costs?: number;
    total_closing_costs_pct?: number;
    total_investment?: number;
    apartment_cold_rent_monthly?: number;
    total_cold_rent_monthly?: number;
    allocable_costs_monthly?: number;
    warm_rent_monthly?: number;
    non_allocable_costs_monthly?: number;
    total_hausgeld_monthly?: number;
    non_allocable_as_pct_of_cold_rent?: number;
    afa_basis?: number;
    annual_afa?: number;
    monthly_afa_display?: number;
    loan_amount?: number;
    equity?: number;
    annual_debt_service?: number;
    monthly_debt_service?: number;
    monthly_interest_yr1?: number;
    monthly_repayment_yr1?: number;
    net_cold_rent_annual?: number;
    gross_rental_yield?: number;
    factor_cold_rent_vs_price?: number;
    monthly_cashflow_pretax?: number;
    monthly_taxable_property_income?: number;
    monthly_tax_benefit?: number;
    monthly_cashflow_after_tax?: number;
    personal_taxable_income?: number;
    base_income_tax?: number;
    avg_tax_rate_display?: number;
    personal_marginal_tax_rate?: number;
    total_operational_cf?: number;
    total_financing_cf?: number;
    total_net_cf_before_tax?: number;
    total_net_cf_after_tax?: number;
    total_equity_invested?: number;
    final_equity_kpi?: number;
    annual_rows?: Array<AnnualCashflowRowResponse>;
};

export type PropertyEvaluationCreate = {
    name?: (string | null);
    journey_step_id?: (string | null);
    /**
     * Full PropertyEvaluationState from frontend
     */
    inputs: {
        [key: string]: unknown;
    };
};

export type PropertyEvaluationListResponse = {
    data: Array<PropertyEvaluationSummary>;
    count: number;
};

export type PropertyEvaluationResponse = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    journey_step_id?: (string | null);
    purchase_price: number;
    square_meters: number;
    state_code?: (string | null);
    cashflow_after_tax: number;
    gross_rental_yield: number;
    return_on_equity: number;
    is_positive_cashflow: boolean;
    inputs: {
        [key: string]: unknown;
    };
    results: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type PropertyEvaluationSummary = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    purchase_price: number;
    cashflow_after_tax: number;
    gross_rental_yield: number;
    is_positive_cashflow: boolean;
    created_at: string;
};

/**
 * Property goals and preferences from Step 1.
 */
export type PropertyGoals = {
    preferred_property_type?: (string | null);
    budget_min_euros?: (number | null);
    budget_max_euros?: (number | null);
    min_rooms?: (number | null);
    min_bathrooms?: (number | null);
    preferred_floor?: (string | null);
    has_elevator_required?: boolean;
    features?: Array<(string)>;
    min_size_sqm?: (number | null);
    max_size_sqm?: (number | null);
    additional_notes?: (string | null);
    property_use?: ('live_in' | 'rent_out' | null);
    preferred_area?: (string | null);
    is_completed?: boolean;
};

/**
 * Schema for updating property goals.
 */
export type PropertyGoalsUpdate = {
    preferred_property_type?: (string | null);
    budget_min_euros?: (number | null);
    budget_max_euros?: (number | null);
    min_rooms?: (number | null);
    min_bathrooms?: (number | null);
    preferred_floor?: (string | null);
    has_elevator_required?: (boolean | null);
    features?: (Array<(string)> | null);
    min_size_sqm?: (number | null);
    max_size_sqm?: (number | null);
    additional_notes?: (string | null);
    property_use?: ('live_in' | 'rent_out' | null);
    preferred_area?: (string | null);
    is_completed?: (boolean | null);
};

/**
 * Types of properties.
 */
export type PropertyType = 'apartment' | 'house' | 'land' | 'commercial';

/**
 * Property types a law applies to.
 */
export type PropertyTypeApplicability = 'all' | 'apartment' | 'house' | 'land' | 'commercial';

/**
 * Answers from the onboarding questionnaire.
 */
export type QuestionnaireAnswers = {
    property_type: PropertyType;
    property_location: string;
    financing_type: FinancingType;
    is_first_time_buyer?: boolean;
    has_german_residency?: boolean;
    budget_euros?: (number | null);
    budget_min_euros?: (number | null);
    target_purchase_date?: (string | null);
    property_use?: ('live_in' | 'rent_out' | null);
};

/**
 * Schema for token refresh request.
 */
export type RefreshTokenRequest = {
    refresh_token: string;
};

/**
 * Schema for user registration.
 *
 * Password requirements:
 * - Minimum 8 characters
 * - At least 1 uppercase letter
 * - At least 1 number
 */
export type RegisterRequest = {
    email: string;
    password: string;
    full_name?: (string | null);
    citizenship?: (string | null);
};

/**
 * Schema for registration response.
 */
export type RegisterResponse = {
    id: string;
    email: string;
    full_name?: (string | null);
    citizenship?: (string | null);
    email_verified?: boolean;
    created_at: string;
};

/**
 * Response for a rent estimate query.
 */
export type RentEstimateResponse = {
    estimated_rent_per_sqm?: (number | null);
    rent_range?: (RentRange | null);
    source?: (string | null);
    confidence: 'high' | 'medium' | 'low';
    city?: (string | null);
    state_code?: (string | null);
    monthly_rent?: (number | null);
};

export type confidence = 'high' | 'medium' | 'low';

/**
 * Min/max rent per sqm range.
 */
export type RentRange = {
    min: number;
    max: number;
};

/**
 * Schema for resending verification email.
 */
export type ResendVerificationRequest = {
    email: string;
};

/**
 * Schema for password reset request.
 *
 * Password requirements:
 * - Minimum 8 characters
 * - At least 1 uppercase letter
 * - At least 1 number
 */
export type ResetPasswordRequest = {
    token: string;
    new_password: string;
};

/**
 * Schema for password reset response.
 */
export type ResetPasswordResponse = {
    message: string;
};

/**
 * Request schema for submitting a review.
 */
export type ReviewCreateRequest = {
    rating: number;
    comment?: (string | null);
    service_used?: (ServiceType | null);
    language_used?: (string | null);
    would_recommend?: (boolean | null);
    response_time_rating?: (number | null);
};

/**
 * Response schema for a professional review.
 */
export type ReviewResponse = {
    id: string;
    professional_id: string;
    rating: number;
    comment?: (string | null);
    service_used?: (ServiceType | null);
    language_used?: (string | null);
    would_recommend?: (boolean | null);
    response_time_rating?: (number | null);
    created_at: string;
};

/**
 * Risk level for translated terms.
 */
export type RiskLevel = 'none' | 'low' | 'medium' | 'high';

/**
 * Request to create/calculate an ROI analysis.
 */
export type ROICalculationCreate = {
    name?: (string | null);
    /**
     * Property purchase price in EUR
     */
    purchase_price: number;
    /**
     * Down payment in EUR
     */
    down_payment: number;
    /**
     * Monthly rental income in EUR
     */
    monthly_rent: number;
    /**
     * Monthly operating expenses in EUR
     */
    monthly_expenses: number;
    /**
     * Expected annual appreciation %
     */
    annual_appreciation: number;
    /**
     * Expected vacancy rate %
     */
    vacancy_rate: number;
    /**
     * Annual mortgage interest rate %
     */
    mortgage_rate: number;
    /**
     * Mortgage term in years
     */
    mortgage_term: number;
};

/**
 * List of saved ROI calculations.
 */
export type ROICalculationListResponse = {
    data: Array<ROICalculationSummary>;
    count: number;
};

/**
 * Full response for a saved ROI calculation.
 */
export type ROICalculationResponse = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    purchase_price: number;
    down_payment: number;
    monthly_rent: number;
    monthly_expenses: number;
    annual_appreciation: number;
    vacancy_rate: number;
    mortgage_rate: number;
    mortgage_term: number;
    gross_rental_income: number;
    net_operating_income: number;
    annual_cash_flow: number;
    monthly_mortgage_payment: number;
    gross_yield: number;
    net_yield: number;
    cap_rate: number;
    cash_on_cash_return: number;
    investment_grade: number;
    investment_grade_label: string;
    projections: Array<ProjectionYear>;
    created_at: string;
};

/**
 * Summary for list views.
 */
export type ROICalculationSummary = {
    id: string;
    name?: (string | null);
    share_id?: (string | null);
    purchase_price: number;
    investment_grade: number;
    investment_grade_label: string;
    annual_cash_flow: number;
    created_at: string;
};

/**
 * Request to compare multiple ROI scenarios.
 */
export type ROICompareRequest = {
    /**
     * 2-4 scenarios to compare
     */
    scenarios: Array<ROICalculationCreate>;
};

/**
 * Response for ROI scenario comparison.
 */
export type ROICompareResponse = {
    scenarios: Array<ROICompareResultItem>;
};

/**
 * Single scenario result in a comparison.
 */
export type ROICompareResultItem = {
    name?: (string | null);
    purchase_price: number;
    down_payment: number;
    monthly_rent: number;
    gross_rental_income: number;
    net_operating_income: number;
    annual_cash_flow: number;
    monthly_mortgage_payment: number;
    gross_yield: number;
    net_yield: number;
    cap_rate: number;
    cash_on_cash_return: number;
    investment_grade: number;
    investment_grade_label: string;
    projections: Array<ProjectionYear>;
};

/**
 * Brief calculation info for dashboard lists.
 */
export type SavedCalculationSummary = {
    id: string;
    name?: (string | null);
    calculator_type: string;
    headline_value: string;
    created_at: string;
};

/**
 * Brief document info for dashboard lists.
 */
export type SavedDocumentSummary = {
    id: string;
    original_filename: string;
    document_type: string;
    status: string;
    created_at: string;
};

/**
 * Calculated results for a single ownership scenario (private or GmbH).
 */
export type ScenarioResult = {
    effective_tax_rate: number;
    year1_tax: number;
    year1_net_income: number;
    total_net_rental_income: number;
    exit_property_value: number;
    capital_gains: number;
    capital_gains_tax: number;
    net_exit_proceeds: number;
    total_wealth: number;
    projections: Array<YearProjection>;
};

/**
 * A single search result item from any content type.
 */
export type SearchResultItem = {
    id: string;
    title: string;
    snippet: string;
    result_type: 'law' | 'article';
    url_path: string;
};

export type result_type = 'law' | 'article';

/**
 * Types of services a professional can provide.
 */
export type ServiceType = 'buying' | 'selling' | 'rental' | 'tax' | 'legal';

/**
 * Cost breakdown for a single state in comparison view.
 */
export type StateComparisonItem = {
    state_code: string;
    state_name: string;
    transfer_tax_rate: number;
    transfer_tax: number;
    notary_fee: number;
    land_registry_fee: number;
    agent_commission: number;
    total_cost: number;
};

/**
 * Response for state-by-state comparison.
 */
export type StateComparisonResponse = {
    property_price: number;
    include_agent: boolean;
    data: Array<StateComparisonItem>;
};

/**
 * Transfer tax rate for a German state.
 */
export type StateRate = {
    state_code: string;
    state_name: string;
    transfer_tax_rate: number;
};

/**
 * Response containing all state rates and cost defaults.
 */
export type StateRatesResponse = {
    data: Array<StateRate>;
    cost_defaults: CostDefaults;
};

/**
 * Response schema for state variations.
 */
export type StateVariationResponse = {
    state_code: string;
    state_name: string;
    variation_title: string;
    variation_value?: (string | null);
    variation_description: string;
    effective_date?: (string | null);
    id: string;
};

/**
 * Status of a journey step.
 */
export type StepStatus = 'not_started' | 'in_progress' | 'completed' | 'skipped';

/**
 * Current subscription status.
 */
export type SubscriptionResponse = {
    tier: SubscriptionTier;
    stripe_customer_id?: (string | null);
    status?: (string | null);
};

/**
 * User subscription tier levels.
 */
export type SubscriptionTier = 'free' | 'premium' | 'enterprise';

/**
 * Supported languages for translation.
 */
export type SupportedLanguage = 'de' | 'en' | 'fr' | 'es' | 'it' | 'pl' | 'tr' | 'ru' | 'ar' | 'zh-Hans';

/**
 * Information about a supported language.
 */
export type SupportedLanguageInfo = {
    code: string;
    name: string;
};

/**
 * Response with list of supported languages.
 */
export type SupportedLanguagesResponse = {
    languages: Array<SupportedLanguageInfo>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Types of portfolio transactions.
 */
export type TransactionType = 'rent_income' | 'operating_expense' | 'maintenance' | 'insurance' | 'hausgeld' | 'mortgage_interest' | 'tax_payment' | 'other_income' | 'other_expense';

/**
 * A single page of translated content.
 */
export type TranslatedPage = {
    page_number: number;
    original_text: string;
    translated_text: string;
};

/**
 * Request schema for text translation.
 */
export type TranslationRequest = {
    /**
     * Text to translate
     */
    text: string;
    /**
     * Source language code
     */
    source_language?: SupportedLanguage;
    /**
     * Target language code
     */
    target_language?: SupportedLanguage;
    /**
     * Include warnings for legal/financial terms
     */
    include_legal_warnings?: boolean;
};

/**
 * Response schema for text translation.
 */
export type TranslationResponse = {
    /**
     * Translation result
     */
    translation: TranslationResult;
    /**
     * Warnings about legal/financial terms
     */
    legal_warnings?: Array<LegalTermWarning>;
    /**
     * Whether the translation requires manual review
     */
    requires_review?: boolean;
    /**
     * Number of characters translated
     */
    character_count: number;
};

/**
 * Result of a single text translation.
 */
export type TranslationResult = {
    /**
     * Original text
     */
    original_text: string;
    /**
     * Translated text
     */
    translated_text: string;
    /**
     * Detected or specified source language
     */
    source_language: string;
    /**
     * Target language
     */
    target_language: string;
    /**
     * Confidence score of the translation (0-1)
     */
    confidence: number;
};

/**
 * Request body for email unsubscribe.
 */
export type UnsubscribeRequest = {
    token: string;
};

/**
 * Response for email unsubscribe.
 */
export type UnsubscribeResponse = {
    message: string;
    notification_type: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    citizenship?: (string | null);
    password: string;
};

/**
 * Schema for GDPR-compliant user data export.
 *
 * Contains all user data in a portable format as required by
 * GDPR Article 20 (Right to Data Portability).
 */
export type UserDataExport = {
    export_date: string;
    export_format_version?: string;
    id: string;
    email: string;
    full_name?: (string | null);
    citizenship?: (string | null);
    is_active: boolean;
    email_verified: boolean;
    onboarding_completed?: boolean;
    onboarding_persona?: (string | null);
    avatar_url?: (string | null);
    subscription_tier: string;
    created_at: string;
    updated_at?: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    citizenship?: (string | null);
    id: string;
    email_verified?: boolean;
    onboarding_completed?: boolean;
    onboarding_persona?: (string | null);
    avatar_url?: (string | null);
    subscription_tier?: SubscriptionTier;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    citizenship?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    citizenship?: (string | null);
    onboarding_completed?: (boolean | null);
    onboarding_persona?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Schema for email verification request.
 */
export type VerifyEmailRequest = {
    token: string;
};

/**
 * Schema for email verification response.
 */
export type VerifyEmailResponse = {
    message: string;
    email_verified: boolean;
};

/**
 * Webhook processing response.
 */
export type WebhookResponse = {
    received: boolean;
};

/**
 * Single year projection for one ownership scenario.
 */
export type YearProjection = {
    year: number;
    rental_income: number;
    tax: number;
    net_income_after_tax: number;
    cumulative_net_income: number;
    property_value: number;
};

export type ArticlesListArticlesData = {
    category?: (ArticleCategory | null);
    difficultyLevel?: (DifficultyLevel | null);
    page?: number;
    pageSize?: number;
};

export type ArticlesListArticlesResponse = (ArticleListResponse);

export type ArticlesCreateArticleData = {
    requestBody: ArticleCreateRequest;
};

export type ArticlesCreateArticleResponse = (ArticleDetailResponse);

export type ArticlesSearchArticlesData = {
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type ArticlesSearchArticlesResponse = (ArticleSearchResponse);

export type ArticlesGetCategoriesResponse = (Array<ArticleCategoryInfo>);

export type ArticlesGetArticleData = {
    slug: string;
};

export type ArticlesGetArticleResponse = (ArticleDetailResponse);

export type ArticlesRateArticleData = {
    requestBody: ArticleRatingRequest;
    slug: string;
};

export type ArticlesRateArticleResponse = (ArticleRatingResponse);

export type ArticlesUpdateArticleData = {
    articleId: string;
    requestBody: ArticleUpdateRequest;
};

export type ArticlesUpdateArticleResponse = (ArticleDetailResponse);

export type ArticlesDeleteArticleData = {
    articleId: string;
};

export type ArticlesDeleteArticleResponse = (void);

export type AuthRegisterData = {
    requestBody: RegisterRequest;
};

export type AuthRegisterResponse = (RegisterResponse);

export type AuthLoginData = {
    requestBody: LoginRequest;
};

export type AuthLoginResponse = (AuthToken);

export type AuthRefreshTokenData = {
    requestBody: RefreshTokenRequest;
};

export type AuthRefreshTokenResponse = (AuthToken);

export type AuthLogoutData = {
    requestBody: LogoutRequest;
};

export type AuthLogoutResponse = (void);

export type AuthVerifyEmailData = {
    requestBody: VerifyEmailRequest;
};

export type AuthVerifyEmailResponse = (VerifyEmailResponse);

export type AuthResendVerificationData = {
    requestBody: ResendVerificationRequest;
};

export type AuthResendVerificationResponse = (VerifyEmailResponse);

export type AuthForgotPasswordData = {
    requestBody: ForgotPasswordRequest;
};

export type AuthForgotPasswordResponse = (ForgotPasswordResponse);

export type AuthResetPasswordData = {
    requestBody: ResetPasswordRequest;
};

export type AuthResetPasswordResponse = (ResetPasswordResponse);

export type CalculatorsGetStateRatesResponse = (StateRatesResponse);

export type CalculatorsCompareStatesData = {
    /**
     * Include agent commission
     */
    includeAgent?: boolean;
    /**
     * Property price in EUR
     */
    price: number;
};

export type CalculatorsCompareStatesResponse = (StateComparisonResponse);

export type CalculatorsGetSharedCalculationData = {
    shareId: string;
};

export type CalculatorsGetSharedCalculationResponse = (HiddenCostCalculationResponse);

export type CalculatorsListCalculationsResponse = (HiddenCostCalculationListResponse);

export type CalculatorsSaveCalculationData = {
    requestBody: HiddenCostCalculationCreate;
};

export type CalculatorsSaveCalculationResponse = (HiddenCostCalculationResponse);

export type CalculatorsGetCalculationData = {
    calcId: string;
};

export type CalculatorsGetCalculationResponse = (HiddenCostCalculationResponse);

export type CalculatorsDeleteCalculationData = {
    calcId: string;
};

export type CalculatorsDeleteCalculationResponse = (void);

export type CalculatorsCompareRoiScenariosData = {
    requestBody: ROICompareRequest;
};

export type CalculatorsCompareRoiScenariosResponse = (ROICompareResponse);

export type CalculatorsGetSharedRoiCalculationData = {
    shareId: string;
};

export type CalculatorsGetSharedRoiCalculationResponse = (ROICalculationResponse);

export type CalculatorsListRoiCalculationsResponse = (ROICalculationListResponse);

export type CalculatorsSaveRoiCalculationData = {
    requestBody: ROICalculationCreate;
};

export type CalculatorsSaveRoiCalculationResponse = (ROICalculationResponse);

export type CalculatorsGetRoiCalculationData = {
    calcId: string;
};

export type CalculatorsGetRoiCalculationResponse = (ROICalculationResponse);

export type CalculatorsDeleteRoiCalculationData = {
    calcId: string;
};

export type CalculatorsDeleteRoiCalculationResponse = (void);

export type CalculatorsGetSharedPropertyEvaluationData = {
    shareId: string;
};

export type CalculatorsGetSharedPropertyEvaluationResponse = (PropertyEvaluationResponse);

export type CalculatorsListStepPropertyEvaluationsData = {
    stepId: string;
};

export type CalculatorsListStepPropertyEvaluationsResponse = (PropertyEvaluationListResponse);

export type CalculatorsCalculatePropertyEvaluationData = {
    requestBody: PropertyEvaluationCalculateRequest;
};

export type CalculatorsCalculatePropertyEvaluationResponse = (PropertyEvaluationCalculateResponse);

export type CalculatorsListPropertyEvaluationsResponse = (PropertyEvaluationListResponse);

export type CalculatorsSavePropertyEvaluationData = {
    requestBody: PropertyEvaluationCreate;
};

export type CalculatorsSavePropertyEvaluationResponse = (PropertyEvaluationResponse);

export type CalculatorsGetPropertyEvaluationData = {
    evalId: string;
};

export type CalculatorsGetPropertyEvaluationResponse = (PropertyEvaluationResponse);

export type CalculatorsDeletePropertyEvaluationData = {
    evalId: string;
};

export type CalculatorsDeletePropertyEvaluationResponse = (void);

export type CalculatorsCalculateOwnershipComparisonData = {
    requestBody: OwnershipComparisonRequest;
};

export type CalculatorsCalculateOwnershipComparisonResponse = (OwnershipComparisonResponse);

export type CalculatorsGetSharedOwnershipComparisonData = {
    shareId: string;
};

export type CalculatorsGetSharedOwnershipComparisonResponse = (OwnershipComparisonSavedResponse);

export type CalculatorsListOwnershipComparisonsResponse = (OwnershipComparisonListResponse);

export type CalculatorsSaveOwnershipComparisonData = {
    requestBody: OwnershipComparisonRequest;
};

export type CalculatorsSaveOwnershipComparisonResponse = (OwnershipComparisonSavedResponse);

export type CalculatorsGetOwnershipComparisonData = {
    calcId: string;
};

export type CalculatorsGetOwnershipComparisonResponse = (OwnershipComparisonSavedResponse);

export type CalculatorsDeleteOwnershipComparisonData = {
    calcId: string;
};

export type CalculatorsDeleteOwnershipComparisonResponse = (void);

export type DashboardGetDashboardOverviewResponse = (DashboardOverviewResponse);

export type DocumentsUploadDocumentData = {
    formData: Body_documents_upload_document;
    journeyStepId?: (string | null);
};

export type DocumentsUploadDocumentResponse = (DocumentUploadResponse);

export type DocumentsGetUsageResponse = (DocumentUsageResponse);

export type DocumentsGetSharedDocumentData = {
    shareId: string;
};

export type DocumentsGetSharedDocumentResponse = (DocumentDetailResponse);

export type DocumentsGetDocumentsByStepData = {
    stepId: string;
};

export type DocumentsGetDocumentsByStepResponse = (Array<DocumentSummary>);

export type DocumentsListDocumentsData = {
    documentType?: (DocumentType | null);
    page?: number;
    pageSize?: number;
    search?: (string | null);
    status?: (DocumentStatus | null);
};

export type DocumentsListDocumentsResponse = (DocumentListResponse);

export type DocumentsGetDocumentData = {
    documentId: string;
};

export type DocumentsGetDocumentResponse = (DocumentDetailResponse);

export type DocumentsDeleteDocumentData = {
    documentId: string;
};

export type DocumentsDeleteDocumentResponse = (void);

export type DocumentsShareDocumentData = {
    documentId: string;
};

export type DocumentsShareDocumentResponse = (DocumentShareResponse);

export type DocumentsGetDocumentTranslationData = {
    documentId: string;
};

export type DocumentsGetDocumentTranslationResponse = (DocumentTranslationResponse);

export type DocumentsGetDocumentStatusData = {
    documentId: string;
};

export type DocumentsGetDocumentStatusResponse = (DocumentStatusResponse);

export type FeedbackSubmitFeedbackData = {
    requestBody: FeedbackCreate;
};

export type FeedbackSubmitFeedbackResponse = (FeedbackResponse);

export type FinancingGetSharedAssessmentData = {
    shareId: string;
};

export type FinancingGetSharedAssessmentResponse = (FinancingAssessmentResponse);

export type FinancingListAssessmentsResponse = (FinancingAssessmentListResponse);

export type FinancingSaveAssessmentData = {
    requestBody: FinancingAssessmentCreate;
};

export type FinancingSaveAssessmentResponse = (FinancingAssessmentResponse);

export type FinancingGetAssessmentData = {
    assessmentId: string;
};

export type FinancingGetAssessmentResponse = (FinancingAssessmentResponse);

export type FinancingDeleteAssessmentData = {
    assessmentId: string;
};

export type FinancingDeleteAssessmentResponse = (void);

export type GlossaryListTermsData = {
    category?: (GlossaryCategory | null);
    page?: number;
    pageSize?: number;
};

export type GlossaryListTermsResponse = (GlossaryListResponse);

export type GlossarySearchGlossaryData = {
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type GlossarySearchGlossaryResponse = (GlossarySearchResponse);

export type GlossaryListCategoriesResponse = (GlossaryCategoriesResponse);

export type GlossaryGetTermData = {
    slug: string;
};

export type GlossaryGetTermResponse = (GlossaryTermDetail);

export type JourneysCreateJourneyData = {
    requestBody: JourneyCreate;
};

export type JourneysCreateJourneyResponse = (JourneyResponse);

export type JourneysListJourneysData = {
    activeOnly?: boolean;
};

export type JourneysListJourneysResponse = (JourneysListResponse);

export type JourneysGetJourneyData = {
    journeyId: string;
};

export type JourneysGetJourneyResponse = (JourneyDetailResponse);

export type JourneysUpdateJourneyData = {
    journeyId: string;
    requestBody: JourneyUpdate;
};

export type JourneysUpdateJourneyResponse = (JourneyResponse);

export type JourneysDeleteJourneyData = {
    journeyId: string;
};

export type JourneysDeleteJourneyResponse = (void);

export type JourneysGetJourneyProgressData = {
    journeyId: string;
};

export type JourneysGetJourneyProgressResponse = (JourneyProgressResponse);

export type JourneysGetNextStepData = {
    journeyId: string;
};

export type JourneysGetNextStepResponse = (NextStepResponse);

export type JourneysUpdateStepStatusData = {
    journeyId: string;
    requestBody: JourneyStepUpdate;
    stepId: string;
};

export type JourneysUpdateStepStatusResponse = (JourneyStepResponse);

export type JourneysUpdateTaskStatusData = {
    journeyId: string;
    requestBody: JourneyTaskUpdate;
    stepId: string;
    taskId: string;
};

export type JourneysUpdateTaskStatusResponse = (JourneyTaskResponse);

export type JourneysGetPropertyGoalsData = {
    journeyId: string;
};

export type JourneysGetPropertyGoalsResponse = (PropertyGoals);

export type JourneysUpdatePropertyGoalsData = {
    journeyId: string;
    requestBody: PropertyGoalsUpdate;
};

export type JourneysUpdatePropertyGoalsResponse = (PropertyGoals);

export type LawsListLawsData = {
    category?: (LawCategory | null);
    page?: number;
    pageSize?: number;
    propertyType?: (PropertyTypeApplicability | null);
    /**
     * German state code
     */
    state?: (string | null);
};

export type LawsListLawsResponse = (LawListResponse);

export type LawsSearchLawsData = {
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type LawsSearchLawsResponse = (LawSearchResponse);

export type LawsGetCategoriesResponse = ({
    [key: string]: unknown;
});

export type LawsGetLawsForJourneyStepData = {
    stepContentKey: string;
};

export type LawsGetLawsForJourneyStepResponse = (JourneyStepLawsResponse);

export type LawsGetBookmarksResponse = (BookmarkListResponse);

export type LawsGetLawData = {
    lawId: string;
};

export type LawsGetLawResponse = (LawDetailResponse);

export type LawsCreateBookmarkData = {
    lawId: string;
    requestBody: BookmarkCreate;
};

export type LawsCreateBookmarkResponse = (BookmarkResponse);

export type LawsDeleteBookmarkData = {
    lawId: string;
};

export type LawsDeleteBookmarkResponse = (void);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    requestBody: PasswordRecoveryRequest;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    requestBody: PasswordRecoveryRequest;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MarketGetRentEstimateData = {
    /**
     * Year the building was constructed
     */
    buildingYear?: (number | null);
    /**
     * German 5-digit postcode
     */
    postcode: string;
    /**
     * Property size in m²
     */
    sizeSqm?: (number | null);
};

export type MarketGetRentEstimateResponse = (RentEstimateResponse);

export type MarketListAreasResponse = (AreaListResponse);

export type MarketCompareAreasData = {
    /**
     * Area keys to compare (2–4)
     */
    keys: Array<(string)>;
};

export type MarketCompareAreasResponse = (ComparisonResponse);

export type NotificationsListNotificationsData = {
    limit?: number;
    offset?: number;
    unreadOnly?: boolean;
};

export type NotificationsListNotificationsResponse = (NotificationListResponse);

export type NotificationsMarkAllNotificationsReadResponse = (Message);

export type NotificationsGetNotificationPreferencesResponse = (NotificationPreferencesResponse);

export type NotificationsUpdateNotificationPreferencesData = {
    requestBody: NotificationPreferencesUpdate;
};

export type NotificationsUpdateNotificationPreferencesResponse = (NotificationPreferencesResponse);

export type NotificationsMarkNotificationReadData = {
    notificationId: string;
};

export type NotificationsMarkNotificationReadResponse = (NotificationResponse);

export type NotificationsDeleteNotificationData = {
    notificationId: string;
};

export type NotificationsDeleteNotificationResponse = (void);

export type NotificationsUnsubscribeData = {
    requestBody: UnsubscribeRequest;
};

export type NotificationsUnsubscribeResponse = (UnsubscribeResponse);

export type PortfolioListPropertiesResponse = (PortfolioPropertyListResponse);

export type PortfolioCreatePropertyData = {
    requestBody: PortfolioPropertyCreate;
};

export type PortfolioCreatePropertyResponse = (PortfolioPropertyResponse);

export type PortfolioCreatePropertyFromJourneyData = {
    journeyId: string;
};

export type PortfolioCreatePropertyFromJourneyResponse = (PortfolioPropertyResponse);

export type PortfolioGetPropertyData = {
    propertyId: string;
};

export type PortfolioGetPropertyResponse = (PortfolioPropertyResponse);

export type PortfolioUpdatePropertyData = {
    propertyId: string;
    requestBody: PortfolioPropertyUpdate;
};

export type PortfolioUpdatePropertyResponse = (PortfolioPropertyResponse);

export type PortfolioDeletePropertyData = {
    propertyId: string;
};

export type PortfolioDeletePropertyResponse = (void);

export type PortfolioCreateTransactionData = {
    propertyId: string;
    requestBody: PortfolioTransactionCreate;
};

export type PortfolioCreateTransactionResponse = (PortfolioTransactionResponse);

export type PortfolioListTransactionsData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    propertyId: string;
};

export type PortfolioListTransactionsResponse = (PortfolioTransactionListResponse);

export type PortfolioDeleteTransactionData = {
    transactionId: string;
};

export type PortfolioDeleteTransactionResponse = (void);

export type PortfolioGetCostSummaryData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    propertyId: string;
};

export type PortfolioGetCostSummaryResponse = (CostSummaryResponse);

export type PortfolioGetPortfolioPerformanceResponse = (PortfolioPerformanceResponse);

export type PortfolioGetPortfolioSummaryResponse = (PortfolioSummaryResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfessionalsGetFilterOptionsResponse = ({
    [key: string]: unknown;
});

export type ProfessionalsListProfessionalsData = {
    city?: (string | null);
    language?: (string | null);
    minRating?: (number | null);
    page?: number;
    pageSize?: number;
    sortBy?: ('rating' | 'reviews' | 'recommended' | null);
    type?: (string | null);
};

export type ProfessionalsListProfessionalsResponse = (ProfessionalListResponse);

export type ProfessionalsGetProfessionalData = {
    professionalId: string;
};

export type ProfessionalsGetProfessionalResponse = (ProfessionalDetailResponse);

export type ProfessionalsCreateReviewData = {
    professionalId: string;
    requestBody: ReviewCreateRequest;
};

export type ProfessionalsCreateReviewResponse = (ReviewResponse);

export type SearchSearchData = {
    /**
     * Max results per type
     */
    limit?: number;
    /**
     * Search query
     */
    q: string;
};

export type SearchSearchResponse = (GlobalSearchResponse);

export type SubscriptionsGetCurrentSubscriptionResponse = (SubscriptionResponse);

export type SubscriptionsCreateCheckoutSessionData = {
    requestBody: CreateCheckoutRequest;
};

export type SubscriptionsCreateCheckoutSessionResponse = (CheckoutResponse);

export type SubscriptionsCreatePortalSessionData = {
    requestBody: PortalRequest;
};

export type SubscriptionsCreatePortalSessionResponse = (PortalResponse);

export type SubscriptionsHandleWebhookData = {
    stripeSignature: string;
};

export type SubscriptionsHandleWebhookResponse = (WebhookResponse);

export type SubscriptionsCancelSubscriptionResponse = (SubscriptionResponse);

export type TranslationsTranslateTextData = {
    requestBody: TranslationRequest;
};

export type TranslationsTranslateTextResponse = (TranslationResponse);

export type TranslationsDetectLanguageData = {
    requestBody: LanguageDetectionRequest;
};

export type TranslationsDetectLanguageResponse = (LanguageDetectionResponse);

export type TranslationsBatchTranslateData = {
    requestBody: BatchTranslationRequest;
};

export type TranslationsBatchTranslateResponse = (BatchTranslationResponse);

export type TranslationsGetSupportedLanguagesResponse = (SupportedLanguagesResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (void);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersExportUserDataResponse = (UserDataExport);

export type UsersUploadAvatarData = {
    formData: Body_users_upload_avatar;
};

export type UsersUploadAvatarResponse = (UserPublic);

export type UsersDeleteAvatarResponse = (void);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (void);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);