"""Fix rental investor step phases

Revision ID: d7a8b9c0d1e2
Revises: c5d6e7f8g9h0
Create Date: 2026-04-24 10:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic
revision = "d7a8b9c0d1e2"
down_revision = "c5d6e7f8g9h0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Fix misclassified rental investor steps.
    # Matches by title, not step_number, as step_number can vary across
    # environments. These titles are seeded data and exist only in
    # journey_step rows generated by the journey service seed templates.
    # - "Understand Landlord Obligations": research → rental_setup
    # - "Analyze Rental Yield": research → rental_setup
    # - "Plan Property Management": preparation → ownership
    op.execute(
        """
        UPDATE journey_step
        SET phase = 'rental_setup'
        WHERE title IN ('Understand Landlord Obligations', 'Analyze Rental Yield')
          AND phase IN ('research', 'preparation')
        """
    )
    op.execute(
        """
        UPDATE journey_step
        SET phase = 'ownership'
        WHERE title = 'Plan Property Management'
          AND phase = 'preparation'
        """
    )


def downgrade() -> None:
    # Restore each title to its specific known original phase individually
    # to avoid incorrectly mapping a step that may have had phase='preparation'
    # back to 'research'.
    op.execute(
        """
        UPDATE journey_step
        SET phase = 'research'
        WHERE title = 'Understand Landlord Obligations'
          AND phase = 'rental_setup'
        """
    )
    op.execute(
        """
        UPDATE journey_step
        SET phase = 'research'
        WHERE title = 'Analyze Rental Yield'
          AND phase = 'rental_setup'
        """
    )
    op.execute(
        """
        UPDATE journey_step
        SET phase = 'preparation'
        WHERE title = 'Plan Property Management'
          AND phase = 'ownership'
        """
    )
