/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutJourneysIndexRouteImport } from './routes/_layout/journeys/index'
import { Route as LayoutJourneysNewRouteImport } from './routes/_layout/journeys/new'
import { Route as LayoutJourneysJourneyIdRouteImport } from './routes/_layout/journeys/$journeyId'
import { Route as LayoutLawsIndexRouteImport } from './routes/_layout/laws/index'
import { Route as LayoutLawsBookmarksRouteImport } from './routes/_layout/laws/bookmarks'
import { Route as LayoutLawsLawIdRouteImport } from './routes/_layout/laws/$lawId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJourneysIndexRoute = LayoutJourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJourneysNewRoute = LayoutJourneysNewRouteImport.update({
  id: '/journeys/new',
  path: '/journeys/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJourneysJourneyIdRoute = LayoutJourneysJourneyIdRouteImport.update({
  id: '/journeys/$journeyId',
  path: '/journeys/$journeyId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLawsIndexRoute = LayoutLawsIndexRouteImport.update({
  id: '/laws/',
  path: '/laws/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLawsBookmarksRoute = LayoutLawsBookmarksRouteImport.update({
  id: '/laws/bookmarks',
  path: '/laws/bookmarks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLawsLawIdRoute = LayoutLawsLawIdRouteImport.update({
  id: '/laws/$lawId',
  path: '/laws/$lawId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/journeys/$journeyId': typeof LayoutJourneysJourneyIdRoute
  '/journeys/new': typeof LayoutJourneysNewRoute
  '/journeys/': typeof LayoutJourneysIndexRoute
  '/laws/$lawId': typeof LayoutLawsLawIdRoute
  '/laws/bookmarks': typeof LayoutLawsBookmarksRoute
  '/laws/': typeof LayoutLawsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/journeys/$journeyId': typeof LayoutJourneysJourneyIdRoute
  '/journeys/new': typeof LayoutJourneysNewRoute
  '/journeys': typeof LayoutJourneysIndexRoute
  '/laws/$lawId': typeof LayoutLawsLawIdRoute
  '/laws/bookmarks': typeof LayoutLawsBookmarksRoute
  '/laws': typeof LayoutLawsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/journeys/$journeyId': typeof LayoutJourneysJourneyIdRoute
  '/_layout/journeys/new': typeof LayoutJourneysNewRoute
  '/_layout/journeys/': typeof LayoutJourneysIndexRoute
  '/_layout/laws/$lawId': typeof LayoutLawsLawIdRoute
  '/_layout/laws/bookmarks': typeof LayoutLawsBookmarksRoute
  '/_layout/laws/': typeof LayoutLawsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/journeys/$journeyId'
    | '/journeys/new'
    | '/journeys/'
    | '/laws/$lawId'
    | '/laws/bookmarks'
    | '/laws/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/journeys/$journeyId'
    | '/journeys/new'
    | '/journeys'
    | '/laws/$lawId'
    | '/laws/bookmarks'
    | '/laws'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/journeys/$journeyId'
    | '/_layout/journeys/new'
    | '/_layout/journeys/'
    | '/_layout/laws/$lawId'
    | '/_layout/laws/bookmarks'
    | '/_layout/laws/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/': {
      id: '/_layout/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof LayoutJourneysIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/new': {
      id: '/_layout/journeys/new'
      path: '/journeys/new'
      fullPath: '/journeys/new'
      preLoaderRoute: typeof LayoutJourneysNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/$journeyId': {
      id: '/_layout/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof LayoutJourneysJourneyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/laws/': {
      id: '/_layout/laws/'
      path: '/laws'
      fullPath: '/laws/'
      preLoaderRoute: typeof LayoutLawsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/laws/bookmarks': {
      id: '/_layout/laws/bookmarks'
      path: '/laws/bookmarks'
      fullPath: '/laws/bookmarks'
      preLoaderRoute: typeof LayoutLawsBookmarksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/laws/$lawId': {
      id: '/_layout/laws/$lawId'
      path: '/laws/$lawId'
      fullPath: '/laws/$lawId'
      preLoaderRoute: typeof LayoutLawsLawIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutJourneysJourneyIdRoute: typeof LayoutJourneysJourneyIdRoute
  LayoutJourneysNewRoute: typeof LayoutJourneysNewRoute
  LayoutJourneysIndexRoute: typeof LayoutJourneysIndexRoute
  LayoutLawsLawIdRoute: typeof LayoutLawsLawIdRoute
  LayoutLawsBookmarksRoute: typeof LayoutLawsBookmarksRoute
  LayoutLawsIndexRoute: typeof LayoutLawsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutJourneysJourneyIdRoute: LayoutJourneysJourneyIdRoute,
  LayoutJourneysNewRoute: LayoutJourneysNewRoute,
  LayoutJourneysIndexRoute: LayoutJourneysIndexRoute,
  LayoutLawsLawIdRoute: LayoutLawsLawIdRoute,
  LayoutLawsBookmarksRoute: LayoutLawsBookmarksRoute,
  LayoutLawsIndexRoute: LayoutLawsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
