/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutBankAccountGuideRouteImport } from './routes/_layout/bank-account-guide'
import { Route as LayoutCalculatorsRouteImport } from './routes/_layout/calculators'
import { Route as LayoutContractExplainerRouteImport } from './routes/_layout/contract-explainer'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutMortgageGuideRouteImport } from './routes/_layout/mortgage-guide'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutViewingChecklistRouteImport } from './routes/_layout/viewing-checklist'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsMortgageCalculatorRouteImport } from './routes/tools/mortgage-calculator'
import { Route as ToolsPropertyCostCalculatorRouteImport } from './routes/tools/property-cost-calculator'
import { Route as ToolsRentVsBuyCalculatorRouteImport } from './routes/tools/rent-vs-buy-calculator'
import { Route as ToolsRoiCalculatorRouteImport } from './routes/tools/roi-calculator'
import { Route as LayoutDocumentsIndexRouteImport } from './routes/_layout/documents/index'
import { Route as LayoutDocumentsDocumentIdRouteImport } from './routes/_layout/documents/$documentId'
import { Route as LayoutJourneysIndexRouteImport } from './routes/_layout/journeys/index'
import { Route as LayoutJourneysJourneyIdRouteImport } from './routes/_layout/journeys/$journeyId'
import { Route as LayoutJourneysNewRouteImport } from './routes/_layout/journeys/new'
import { Route as LayoutLawsBookmarksRouteImport } from './routes/_layout/laws/bookmarks'
import { Route as LayoutPortfolioIndexRouteImport } from './routes/_layout/portfolio/index'
import { Route as LayoutPortfolioPropertyIdRouteImport } from './routes/_layout/portfolio/$propertyId'
import { Route as LayoutProfessionalsIndexRouteImport } from './routes/_layout/professionals/index'
import { Route as LayoutProfessionalsProfessionalIdRouteImport } from './routes/_layout/professionals/$professionalId'
import { Route as PublicArticlesIndexRouteImport } from './routes/_public/articles/index'
import { Route as PublicArticlesSlugRouteImport } from './routes/_public/articles/$slug'
import { Route as PublicGlossaryIndexRouteImport } from './routes/_public/glossary/index'
import { Route as PublicGlossarySlugRouteImport } from './routes/_public/glossary/$slug'
import { Route as PublicLawsIndexRouteImport } from './routes/_public/laws/index'
import { Route as PublicLawsLawIdRouteImport } from './routes/_public/laws/$lawId'
import { Route as SharedEvaluationShareIdRouteImport } from './routes/shared/evaluation.$shareId'
import { Route as LayoutJourneysJourneyIdIndexRouteImport } from './routes/_layout/journeys/$journeyId.index'
import { Route as LayoutJourneysJourneyIdPropertyEvaluationRouteImport } from './routes/_layout/journeys/$journeyId.property-evaluation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBankAccountGuideRoute = LayoutBankAccountGuideRouteImport.update({
  id: '/bank-account-guide',
  path: '/bank-account-guide',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalculatorsRoute = LayoutCalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContractExplainerRoute = LayoutContractExplainerRouteImport.update({
  id: '/contract-explainer',
  path: '/contract-explainer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMortgageGuideRoute = LayoutMortgageGuideRouteImport.update({
  id: '/mortgage-guide',
  path: '/mortgage-guide',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewingChecklistRoute = LayoutViewingChecklistRouteImport.update({
  id: '/viewing-checklist',
  path: '/viewing-checklist',
  getParentRoute: () => LayoutRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsMortgageCalculatorRoute = ToolsMortgageCalculatorRouteImport.update({
  id: '/mortgage-calculator',
  path: '/mortgage-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPropertyCostCalculatorRoute =
  ToolsPropertyCostCalculatorRouteImport.update({
    id: '/property-cost-calculator',
    path: '/property-cost-calculator',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsRentVsBuyCalculatorRoute =
  ToolsRentVsBuyCalculatorRouteImport.update({
    id: '/rent-vs-buy-calculator',
    path: '/rent-vs-buy-calculator',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsRoiCalculatorRoute = ToolsRoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const LayoutDocumentsIndexRoute = LayoutDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentsDocumentIdRoute =
  LayoutDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutJourneysIndexRoute = LayoutJourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJourneysJourneyIdRoute = LayoutJourneysJourneyIdRouteImport.update({
  id: '/journeys/$journeyId',
  path: '/journeys/$journeyId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJourneysNewRoute = LayoutJourneysNewRouteImport.update({
  id: '/journeys/new',
  path: '/journeys/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLawsBookmarksRoute = LayoutLawsBookmarksRouteImport.update({
  id: '/laws/bookmarks',
  path: '/laws/bookmarks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPortfolioIndexRoute = LayoutPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPortfolioPropertyIdRoute =
  LayoutPortfolioPropertyIdRouteImport.update({
    id: '/portfolio/$propertyId',
    path: '/portfolio/$propertyId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProfessionalsIndexRoute =
  LayoutProfessionalsIndexRouteImport.update({
    id: '/professionals/',
    path: '/professionals/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProfessionalsProfessionalIdRoute =
  LayoutProfessionalsProfessionalIdRouteImport.update({
    id: '/professionals/$professionalId',
    path: '/professionals/$professionalId',
    getParentRoute: () => LayoutRoute,
  } as any)
const PublicArticlesIndexRoute = PublicArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicArticlesSlugRoute = PublicArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGlossaryIndexRoute = PublicGlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGlossarySlugRoute = PublicGlossarySlugRouteImport.update({
  id: '/glossary/$slug',
  path: '/glossary/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLawsIndexRoute = PublicLawsIndexRouteImport.update({
  id: '/laws/',
  path: '/laws/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLawsLawIdRoute = PublicLawsLawIdRouteImport.update({
  id: '/laws/$lawId',
  path: '/laws/$lawId',
  getParentRoute: () => PublicRoute,
} as any)
const SharedEvaluationShareIdRoute = SharedEvaluationShareIdRouteImport.update({
  id: '/shared/evaluation/$shareId',
  path: '/shared/evaluation/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutJourneysJourneyIdIndexRoute =
  LayoutJourneysJourneyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutJourneysJourneyIdRoute,
  } as any)
const LayoutJourneysJourneyIdPropertyEvaluationRoute =
  LayoutJourneysJourneyIdPropertyEvaluationRouteImport.update({
    id: '/property-evaluation',
    path: '/property-evaluation',
    getParentRoute: () => LayoutJourneysJourneyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/bank-account-guide': typeof LayoutBankAccountGuideRoute
  '/calculators': typeof LayoutCalculatorsRoute
  '/contract-explainer': typeof LayoutContractExplainerRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/mortgage-guide': typeof LayoutMortgageGuideRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/viewing-checklist': typeof LayoutViewingChecklistRoute
  '/tools/mortgage-calculator': typeof ToolsMortgageCalculatorRoute
  '/tools/property-cost-calculator': typeof ToolsPropertyCostCalculatorRoute
  '/tools/rent-vs-buy-calculator': typeof ToolsRentVsBuyCalculatorRoute
  '/tools/roi-calculator': typeof ToolsRoiCalculatorRoute
  '/tools/': typeof ToolsIndexRoute
  '/documents/$documentId': typeof LayoutDocumentsDocumentIdRoute
  '/journeys/$journeyId': typeof LayoutJourneysJourneyIdRouteWithChildren
  '/journeys/new': typeof LayoutJourneysNewRoute
  '/laws/bookmarks': typeof LayoutLawsBookmarksRoute
  '/portfolio/$propertyId': typeof LayoutPortfolioPropertyIdRoute
  '/professionals/$professionalId': typeof LayoutProfessionalsProfessionalIdRoute
  '/articles/$slug': typeof PublicArticlesSlugRoute
  '/glossary/$slug': typeof PublicGlossarySlugRoute
  '/laws/$lawId': typeof PublicLawsLawIdRoute
  '/shared/evaluation/$shareId': typeof SharedEvaluationShareIdRoute
  '/documents/': typeof LayoutDocumentsIndexRoute
  '/journeys/': typeof LayoutJourneysIndexRoute
  '/portfolio/': typeof LayoutPortfolioIndexRoute
  '/professionals/': typeof LayoutProfessionalsIndexRoute
  '/articles/': typeof PublicArticlesIndexRoute
  '/glossary/': typeof PublicGlossaryIndexRoute
  '/laws/': typeof PublicLawsIndexRoute
  '/journeys/$journeyId/property-evaluation': typeof LayoutJourneysJourneyIdPropertyEvaluationRoute
  '/journeys/$journeyId/': typeof LayoutJourneysJourneyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/bank-account-guide': typeof LayoutBankAccountGuideRoute
  '/calculators': typeof LayoutCalculatorsRoute
  '/contract-explainer': typeof LayoutContractExplainerRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/mortgage-guide': typeof LayoutMortgageGuideRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/viewing-checklist': typeof LayoutViewingChecklistRoute
  '/tools/mortgage-calculator': typeof ToolsMortgageCalculatorRoute
  '/tools/property-cost-calculator': typeof ToolsPropertyCostCalculatorRoute
  '/tools/rent-vs-buy-calculator': typeof ToolsRentVsBuyCalculatorRoute
  '/tools/roi-calculator': typeof ToolsRoiCalculatorRoute
  '/tools': typeof ToolsIndexRoute
  '/documents/$documentId': typeof LayoutDocumentsDocumentIdRoute
  '/journeys/new': typeof LayoutJourneysNewRoute
  '/laws/bookmarks': typeof LayoutLawsBookmarksRoute
  '/portfolio/$propertyId': typeof LayoutPortfolioPropertyIdRoute
  '/professionals/$professionalId': typeof LayoutProfessionalsProfessionalIdRoute
  '/articles/$slug': typeof PublicArticlesSlugRoute
  '/glossary/$slug': typeof PublicGlossarySlugRoute
  '/laws/$lawId': typeof PublicLawsLawIdRoute
  '/shared/evaluation/$shareId': typeof SharedEvaluationShareIdRoute
  '/documents': typeof LayoutDocumentsIndexRoute
  '/journeys': typeof LayoutJourneysIndexRoute
  '/portfolio': typeof LayoutPortfolioIndexRoute
  '/professionals': typeof LayoutProfessionalsIndexRoute
  '/articles': typeof PublicArticlesIndexRoute
  '/glossary': typeof PublicGlossaryIndexRoute
  '/laws': typeof PublicLawsIndexRoute
  '/journeys/$journeyId/property-evaluation': typeof LayoutJourneysJourneyIdPropertyEvaluationRoute
  '/journeys/$journeyId': typeof LayoutJourneysJourneyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/bank-account-guide': typeof LayoutBankAccountGuideRoute
  '/_layout/calculators': typeof LayoutCalculatorsRoute
  '/_layout/contract-explainer': typeof LayoutContractExplainerRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/mortgage-guide': typeof LayoutMortgageGuideRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/viewing-checklist': typeof LayoutViewingChecklistRoute
  '/tools/mortgage-calculator': typeof ToolsMortgageCalculatorRoute
  '/tools/property-cost-calculator': typeof ToolsPropertyCostCalculatorRoute
  '/tools/rent-vs-buy-calculator': typeof ToolsRentVsBuyCalculatorRoute
  '/tools/roi-calculator': typeof ToolsRoiCalculatorRoute
  '/tools/': typeof ToolsIndexRoute
  '/_layout/documents/$documentId': typeof LayoutDocumentsDocumentIdRoute
  '/_layout/journeys/$journeyId': typeof LayoutJourneysJourneyIdRouteWithChildren
  '/_layout/journeys/new': typeof LayoutJourneysNewRoute
  '/_layout/laws/bookmarks': typeof LayoutLawsBookmarksRoute
  '/_layout/portfolio/$propertyId': typeof LayoutPortfolioPropertyIdRoute
  '/_layout/professionals/$professionalId': typeof LayoutProfessionalsProfessionalIdRoute
  '/_public/articles/$slug': typeof PublicArticlesSlugRoute
  '/_public/glossary/$slug': typeof PublicGlossarySlugRoute
  '/_public/laws/$lawId': typeof PublicLawsLawIdRoute
  '/shared/evaluation/$shareId': typeof SharedEvaluationShareIdRoute
  '/_layout/documents/': typeof LayoutDocumentsIndexRoute
  '/_layout/journeys/': typeof LayoutJourneysIndexRoute
  '/_layout/portfolio/': typeof LayoutPortfolioIndexRoute
  '/_layout/professionals/': typeof LayoutProfessionalsIndexRoute
  '/_public/articles/': typeof PublicArticlesIndexRoute
  '/_public/glossary/': typeof PublicGlossaryIndexRoute
  '/_public/laws/': typeof PublicLawsIndexRoute
  '/_layout/journeys/$journeyId/property-evaluation': typeof LayoutJourneysJourneyIdPropertyEvaluationRoute
  '/_layout/journeys/$journeyId/': typeof LayoutJourneysJourneyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imprint'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin'
    | '/bank-account-guide'
    | '/calculators'
    | '/contract-explainer'
    | '/dashboard'
    | '/mortgage-guide'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/viewing-checklist'
    | '/tools/mortgage-calculator'
    | '/tools/property-cost-calculator'
    | '/tools/rent-vs-buy-calculator'
    | '/tools/roi-calculator'
    | '/tools/'
    | '/documents/$documentId'
    | '/journeys/$journeyId'
    | '/journeys/new'
    | '/laws/bookmarks'
    | '/portfolio/$propertyId'
    | '/professionals/$professionalId'
    | '/articles/$slug'
    | '/glossary/$slug'
    | '/laws/$lawId'
    | '/shared/evaluation/$shareId'
    | '/documents/'
    | '/journeys/'
    | '/portfolio/'
    | '/professionals/'
    | '/articles/'
    | '/glossary/'
    | '/laws/'
    | '/journeys/$journeyId/property-evaluation'
    | '/journeys/$journeyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imprint'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin'
    | '/bank-account-guide'
    | '/calculators'
    | '/contract-explainer'
    | '/dashboard'
    | '/mortgage-guide'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/viewing-checklist'
    | '/tools/mortgage-calculator'
    | '/tools/property-cost-calculator'
    | '/tools/rent-vs-buy-calculator'
    | '/tools/roi-calculator'
    | '/tools'
    | '/documents/$documentId'
    | '/journeys/new'
    | '/laws/bookmarks'
    | '/portfolio/$propertyId'
    | '/professionals/$professionalId'
    | '/articles/$slug'
    | '/glossary/$slug'
    | '/laws/$lawId'
    | '/shared/evaluation/$shareId'
    | '/documents'
    | '/journeys'
    | '/portfolio'
    | '/professionals'
    | '/articles'
    | '/glossary'
    | '/laws'
    | '/journeys/$journeyId/property-evaluation'
    | '/journeys/$journeyId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_public'
    | '/imprint'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/unsubscribe'
    | '/verify-email'
    | '/_layout/admin'
    | '/_layout/bank-account-guide'
    | '/_layout/calculators'
    | '/_layout/contract-explainer'
    | '/_layout/dashboard'
    | '/_layout/mortgage-guide'
    | '/_layout/notifications'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/viewing-checklist'
    | '/tools/mortgage-calculator'
    | '/tools/property-cost-calculator'
    | '/tools/rent-vs-buy-calculator'
    | '/tools/roi-calculator'
    | '/tools/'
    | '/_layout/documents/$documentId'
    | '/_layout/journeys/$journeyId'
    | '/_layout/journeys/new'
    | '/_layout/laws/bookmarks'
    | '/_layout/portfolio/$propertyId'
    | '/_layout/professionals/$professionalId'
    | '/_public/articles/$slug'
    | '/_public/glossary/$slug'
    | '/_public/laws/$lawId'
    | '/shared/evaluation/$shareId'
    | '/_layout/documents/'
    | '/_layout/journeys/'
    | '/_layout/portfolio/'
    | '/_layout/professionals/'
    | '/_public/articles/'
    | '/_public/glossary/'
    | '/_public/laws/'
    | '/_layout/journeys/$journeyId/property-evaluation'
    | '/_layout/journeys/$journeyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ImprintRoute: typeof ImprintRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  SharedEvaluationShareIdRoute: typeof SharedEvaluationShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bank-account-guide': {
      id: '/_layout/bank-account-guide'
      path: '/bank-account-guide'
      fullPath: '/bank-account-guide'
      preLoaderRoute: typeof LayoutBankAccountGuideRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calculators': {
      id: '/_layout/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof LayoutCalculatorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contract-explainer': {
      id: '/_layout/contract-explainer'
      path: '/contract-explainer'
      fullPath: '/contract-explainer'
      preLoaderRoute: typeof LayoutContractExplainerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mortgage-guide': {
      id: '/_layout/mortgage-guide'
      path: '/mortgage-guide'
      fullPath: '/mortgage-guide'
      preLoaderRoute: typeof LayoutMortgageGuideRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/viewing-checklist': {
      id: '/_layout/viewing-checklist'
      path: '/viewing-checklist'
      fullPath: '/viewing-checklist'
      preLoaderRoute: typeof LayoutViewingChecklistRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/mortgage-calculator': {
      id: '/tools/mortgage-calculator'
      path: '/mortgage-calculator'
      fullPath: '/tools/mortgage-calculator'
      preLoaderRoute: typeof ToolsMortgageCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/property-cost-calculator': {
      id: '/tools/property-cost-calculator'
      path: '/property-cost-calculator'
      fullPath: '/tools/property-cost-calculator'
      preLoaderRoute: typeof ToolsPropertyCostCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/rent-vs-buy-calculator': {
      id: '/tools/rent-vs-buy-calculator'
      path: '/rent-vs-buy-calculator'
      fullPath: '/tools/rent-vs-buy-calculator'
      preLoaderRoute: typeof ToolsRentVsBuyCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/roi-calculator': {
      id: '/tools/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/tools/roi-calculator'
      preLoaderRoute: typeof ToolsRoiCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/_layout/documents/': {
      id: '/_layout/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof LayoutDocumentsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documents/$documentId': {
      id: '/_layout/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof LayoutDocumentsDocumentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/': {
      id: '/_layout/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof LayoutJourneysIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/$journeyId': {
      id: '/_layout/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof LayoutJourneysJourneyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/new': {
      id: '/_layout/journeys/new'
      path: '/journeys/new'
      fullPath: '/journeys/new'
      preLoaderRoute: typeof LayoutJourneysNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/laws/bookmarks': {
      id: '/_layout/laws/bookmarks'
      path: '/laws/bookmarks'
      fullPath: '/laws/bookmarks'
      preLoaderRoute: typeof LayoutLawsBookmarksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio/': {
      id: '/_layout/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof LayoutPortfolioIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio/$propertyId': {
      id: '/_layout/portfolio/$propertyId'
      path: '/portfolio/$propertyId'
      fullPath: '/portfolio/$propertyId'
      preLoaderRoute: typeof LayoutPortfolioPropertyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/professionals/': {
      id: '/_layout/professionals/'
      path: '/professionals'
      fullPath: '/professionals/'
      preLoaderRoute: typeof LayoutProfessionalsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/professionals/$professionalId': {
      id: '/_layout/professionals/$professionalId'
      path: '/professionals/$professionalId'
      fullPath: '/professionals/$professionalId'
      preLoaderRoute: typeof LayoutProfessionalsProfessionalIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_public/articles/': {
      id: '/_public/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof PublicArticlesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/articles/$slug': {
      id: '/_public/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof PublicArticlesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/glossary/': {
      id: '/_public/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof PublicGlossaryIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/glossary/$slug': {
      id: '/_public/glossary/$slug'
      path: '/glossary/$slug'
      fullPath: '/glossary/$slug'
      preLoaderRoute: typeof PublicGlossarySlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/laws/': {
      id: '/_public/laws/'
      path: '/laws'
      fullPath: '/laws/'
      preLoaderRoute: typeof PublicLawsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/laws/$lawId': {
      id: '/_public/laws/$lawId'
      path: '/laws/$lawId'
      fullPath: '/laws/$lawId'
      preLoaderRoute: typeof PublicLawsLawIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/shared/evaluation/$shareId': {
      id: '/shared/evaluation/$shareId'
      path: '/shared/evaluation/$shareId'
      fullPath: '/shared/evaluation/$shareId'
      preLoaderRoute: typeof SharedEvaluationShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/journeys/$journeyId/': {
      id: '/_layout/journeys/$journeyId/'
      path: '/'
      fullPath: '/journeys/$journeyId/'
      preLoaderRoute: typeof LayoutJourneysJourneyIdIndexRouteImport
      parentRoute: typeof LayoutJourneysJourneyIdRoute
    }
    '/_layout/journeys/$journeyId/property-evaluation': {
      id: '/_layout/journeys/$journeyId/property-evaluation'
      path: '/property-evaluation'
      fullPath: '/journeys/$journeyId/property-evaluation'
      preLoaderRoute: typeof LayoutJourneysJourneyIdPropertyEvaluationRouteImport
      parentRoute: typeof LayoutJourneysJourneyIdRoute
    }
  }
}

interface LayoutJourneysJourneyIdRouteChildren {
  LayoutJourneysJourneyIdPropertyEvaluationRoute: typeof LayoutJourneysJourneyIdPropertyEvaluationRoute
  LayoutJourneysJourneyIdIndexRoute: typeof LayoutJourneysJourneyIdIndexRoute
}

const LayoutJourneysJourneyIdRouteChildren: LayoutJourneysJourneyIdRouteChildren =
  {
    LayoutJourneysJourneyIdPropertyEvaluationRoute:
      LayoutJourneysJourneyIdPropertyEvaluationRoute,
    LayoutJourneysJourneyIdIndexRoute: LayoutJourneysJourneyIdIndexRoute,
  }

const LayoutJourneysJourneyIdRouteWithChildren =
  LayoutJourneysJourneyIdRoute._addFileChildren(
    LayoutJourneysJourneyIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBankAccountGuideRoute: typeof LayoutBankAccountGuideRoute
  LayoutCalculatorsRoute: typeof LayoutCalculatorsRoute
  LayoutContractExplainerRoute: typeof LayoutContractExplainerRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutMortgageGuideRoute: typeof LayoutMortgageGuideRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutViewingChecklistRoute: typeof LayoutViewingChecklistRoute
  LayoutDocumentsDocumentIdRoute: typeof LayoutDocumentsDocumentIdRoute
  LayoutJourneysJourneyIdRoute: typeof LayoutJourneysJourneyIdRouteWithChildren
  LayoutJourneysNewRoute: typeof LayoutJourneysNewRoute
  LayoutLawsBookmarksRoute: typeof LayoutLawsBookmarksRoute
  LayoutPortfolioPropertyIdRoute: typeof LayoutPortfolioPropertyIdRoute
  LayoutProfessionalsProfessionalIdRoute: typeof LayoutProfessionalsProfessionalIdRoute
  LayoutDocumentsIndexRoute: typeof LayoutDocumentsIndexRoute
  LayoutJourneysIndexRoute: typeof LayoutJourneysIndexRoute
  LayoutPortfolioIndexRoute: typeof LayoutPortfolioIndexRoute
  LayoutProfessionalsIndexRoute: typeof LayoutProfessionalsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBankAccountGuideRoute: LayoutBankAccountGuideRoute,
  LayoutCalculatorsRoute: LayoutCalculatorsRoute,
  LayoutContractExplainerRoute: LayoutContractExplainerRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutMortgageGuideRoute: LayoutMortgageGuideRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutViewingChecklistRoute: LayoutViewingChecklistRoute,
  LayoutDocumentsDocumentIdRoute: LayoutDocumentsDocumentIdRoute,
  LayoutJourneysJourneyIdRoute: LayoutJourneysJourneyIdRouteWithChildren,
  LayoutJourneysNewRoute: LayoutJourneysNewRoute,
  LayoutLawsBookmarksRoute: LayoutLawsBookmarksRoute,
  LayoutPortfolioPropertyIdRoute: LayoutPortfolioPropertyIdRoute,
  LayoutProfessionalsProfessionalIdRoute:
    LayoutProfessionalsProfessionalIdRoute,
  LayoutDocumentsIndexRoute: LayoutDocumentsIndexRoute,
  LayoutJourneysIndexRoute: LayoutJourneysIndexRoute,
  LayoutPortfolioIndexRoute: LayoutPortfolioIndexRoute,
  LayoutProfessionalsIndexRoute: LayoutProfessionalsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface PublicRouteChildren {
  PublicArticlesSlugRoute: typeof PublicArticlesSlugRoute
  PublicGlossarySlugRoute: typeof PublicGlossarySlugRoute
  PublicLawsLawIdRoute: typeof PublicLawsLawIdRoute
  PublicArticlesIndexRoute: typeof PublicArticlesIndexRoute
  PublicGlossaryIndexRoute: typeof PublicGlossaryIndexRoute
  PublicLawsIndexRoute: typeof PublicLawsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicArticlesSlugRoute: PublicArticlesSlugRoute,
  PublicGlossarySlugRoute: PublicGlossarySlugRoute,
  PublicLawsLawIdRoute: PublicLawsLawIdRoute,
  PublicArticlesIndexRoute: PublicArticlesIndexRoute,
  PublicGlossaryIndexRoute: PublicGlossaryIndexRoute,
  PublicLawsIndexRoute: PublicLawsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface ToolsRouteChildren {
  ToolsMortgageCalculatorRoute: typeof ToolsMortgageCalculatorRoute
  ToolsPropertyCostCalculatorRoute: typeof ToolsPropertyCostCalculatorRoute
  ToolsRentVsBuyCalculatorRoute: typeof ToolsRentVsBuyCalculatorRoute
  ToolsRoiCalculatorRoute: typeof ToolsRoiCalculatorRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsMortgageCalculatorRoute: ToolsMortgageCalculatorRoute,
  ToolsPropertyCostCalculatorRoute: ToolsPropertyCostCalculatorRoute,
  ToolsRentVsBuyCalculatorRoute: ToolsRentVsBuyCalculatorRoute,
  ToolsRoiCalculatorRoute: ToolsRoiCalculatorRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ImprintRoute: ImprintRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  SharedEvaluationShareIdRoute: SharedEvaluationShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
