/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsRoiCalculatorRouteImport } from './routes/tools/roi-calculator'
import { Route as ToolsPropertyCostCalculatorRouteImport } from './routes/tools/property-cost-calculator'
import { Route as ToolsMortgageCalculatorRouteImport } from './routes/tools/mortgage-calculator'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCalculatorsRouteImport } from './routes/_layout/calculators'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProfessionalsIndexRouteImport } from './routes/_layout/professionals/index'
import { Route as LayoutPortfolioIndexRouteImport } from './routes/_layout/portfolio/index'
import { Route as LayoutLawsIndexRouteImport } from './routes/_layout/laws/index'
import { Route as LayoutJourneysIndexRouteImport } from './routes/_layout/journeys/index'
import { Route as LayoutGlossaryIndexRouteImport } from './routes/_layout/glossary/index'
import { Route as LayoutDocumentsIndexRouteImport } from './routes/_layout/documents/index'
import { Route as LayoutArticlesIndexRouteImport } from './routes/_layout/articles/index'
import { Route as SharedEvaluationShareIdRouteImport } from './routes/shared/evaluation.$shareId'
import { Route as LayoutProfessionalsProfessionalIdRouteImport } from './routes/_layout/professionals/$professionalId'
import { Route as LayoutPortfolioPropertyIdRouteImport } from './routes/_layout/portfolio/$propertyId'
import { Route as LayoutLawsBookmarksRouteImport } from './routes/_layout/laws/bookmarks'
import { Route as LayoutLawsLawIdRouteImport } from './routes/_layout/laws/$lawId'
import { Route as LayoutJourneysNewRouteImport } from './routes/_layout/journeys/new'
import { Route as LayoutJourneysJourneyIdRouteImport } from './routes/_layout/journeys/$journeyId'
import { Route as LayoutGlossarySlugRouteImport } from './routes/_layout/glossary/$slug'
import { Route as LayoutDocumentsDocumentIdRouteImport } from './routes/_layout/documents/$documentId'
import { Route as LayoutArticlesSlugRouteImport } from './routes/_layout/articles/$slug'
import { Route as LayoutJourneysJourneyIdIndexRouteImport } from './routes/_layout/journeys/$journeyId.index'
import { Route as LayoutJourneysJourneyIdPropertyEvaluationRouteImport } from './routes/_layout/journeys/$journeyId.property-evaluation'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsRoiCalculatorRoute = ToolsRoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPropertyCostCalculatorRoute =
  ToolsPropertyCostCalculatorRouteImport.update({
    id: '/property-cost-calculator',
    path: '/property-cost-calculator',
    getParentRoute: () => ToolsRoute,
  } as any)
const ToolsMortgageCalculatorRoute = ToolsMortgageCalculatorRouteImport.update({
  id: '/mortgage-calculator',
  path: '/mortgage-calculator',
  getParentRoute: () => ToolsRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCalculatorsRoute = LayoutCalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfessionalsIndexRoute =
  LayoutProfessionalsIndexRouteImport.update({
    id: '/professionals/',
    path: '/professionals/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPortfolioIndexRoute = LayoutPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLawsIndexRoute = LayoutLawsIndexRouteImport.update({
  id: '/laws/',
  path: '/laws/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJourneysIndexRoute = LayoutJourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGlossaryIndexRoute = LayoutGlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentsIndexRoute = LayoutDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutArticlesIndexRoute = LayoutArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => LayoutRoute,
} as any)
const SharedEvaluationShareIdRoute = SharedEvaluationShareIdRouteImport.update({
  id: '/shared/evaluation/$shareId',
  path: '/shared/evaluation/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProfessionalsProfessionalIdRoute =
  LayoutProfessionalsProfessionalIdRouteImport.update({
    id: '/professionals/$professionalId',
    path: '/professionals/$professionalId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPortfolioPropertyIdRoute =
  LayoutPortfolioPropertyIdRouteImport.update({
    id: '/portfolio/$propertyId',
    path: '/portfolio/$propertyId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutLawsBookmarksRoute = LayoutLawsBookmarksRouteImport.update({
  id: '/laws/bookmarks',
  path: '/laws/bookmarks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLawsLawIdRoute = LayoutLawsLawIdRouteImport.update({
  id: '/laws/$lawId',
  path: '/laws/$lawId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJourneysNewRoute = LayoutJourneysNewRouteImport.update({
  id: '/journeys/new',
  path: '/journeys/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJourneysJourneyIdRoute = LayoutJourneysJourneyIdRouteImport.update({
  id: '/journeys/$journeyId',
  path: '/journeys/$journeyId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGlossarySlugRoute = LayoutGlossarySlugRouteImport.update({
  id: '/glossary/$slug',
  path: '/glossary/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentsDocumentIdRoute =
  LayoutDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutArticlesSlugRoute = LayoutArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJourneysJourneyIdIndexRoute =
  LayoutJourneysJourneyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutJourneysJourneyIdRoute,
  } as any)
const LayoutJourneysJourneyIdPropertyEvaluationRoute =
  LayoutJourneysJourneyIdPropertyEvaluationRouteImport.update({
    id: '/property-evaluation',
    path: '/property-evaluation',
    getParentRoute: () => LayoutJourneysJourneyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/calculators': typeof LayoutCalculatorsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/items': typeof LayoutItemsRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/tools/mortgage-calculator': typeof ToolsMortgageCalculatorRoute
  '/tools/property-cost-calculator': typeof ToolsPropertyCostCalculatorRoute
  '/tools/roi-calculator': typeof ToolsRoiCalculatorRoute
  '/tools/': typeof ToolsIndexRoute
  '/articles/$slug': typeof LayoutArticlesSlugRoute
  '/documents/$documentId': typeof LayoutDocumentsDocumentIdRoute
  '/glossary/$slug': typeof LayoutGlossarySlugRoute
  '/journeys/$journeyId': typeof LayoutJourneysJourneyIdRouteWithChildren
  '/journeys/new': typeof LayoutJourneysNewRoute
  '/laws/$lawId': typeof LayoutLawsLawIdRoute
  '/laws/bookmarks': typeof LayoutLawsBookmarksRoute
  '/portfolio/$propertyId': typeof LayoutPortfolioPropertyIdRoute
  '/professionals/$professionalId': typeof LayoutProfessionalsProfessionalIdRoute
  '/shared/evaluation/$shareId': typeof SharedEvaluationShareIdRoute
  '/articles/': typeof LayoutArticlesIndexRoute
  '/documents/': typeof LayoutDocumentsIndexRoute
  '/glossary/': typeof LayoutGlossaryIndexRoute
  '/journeys/': typeof LayoutJourneysIndexRoute
  '/laws/': typeof LayoutLawsIndexRoute
  '/portfolio/': typeof LayoutPortfolioIndexRoute
  '/professionals/': typeof LayoutProfessionalsIndexRoute
  '/journeys/$journeyId/property-evaluation': typeof LayoutJourneysJourneyIdPropertyEvaluationRoute
  '/journeys/$journeyId/': typeof LayoutJourneysJourneyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/calculators': typeof LayoutCalculatorsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/items': typeof LayoutItemsRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/tools/mortgage-calculator': typeof ToolsMortgageCalculatorRoute
  '/tools/property-cost-calculator': typeof ToolsPropertyCostCalculatorRoute
  '/tools/roi-calculator': typeof ToolsRoiCalculatorRoute
  '/tools': typeof ToolsIndexRoute
  '/articles/$slug': typeof LayoutArticlesSlugRoute
  '/documents/$documentId': typeof LayoutDocumentsDocumentIdRoute
  '/glossary/$slug': typeof LayoutGlossarySlugRoute
  '/journeys/new': typeof LayoutJourneysNewRoute
  '/laws/$lawId': typeof LayoutLawsLawIdRoute
  '/laws/bookmarks': typeof LayoutLawsBookmarksRoute
  '/portfolio/$propertyId': typeof LayoutPortfolioPropertyIdRoute
  '/professionals/$professionalId': typeof LayoutProfessionalsProfessionalIdRoute
  '/shared/evaluation/$shareId': typeof SharedEvaluationShareIdRoute
  '/articles': typeof LayoutArticlesIndexRoute
  '/documents': typeof LayoutDocumentsIndexRoute
  '/glossary': typeof LayoutGlossaryIndexRoute
  '/journeys': typeof LayoutJourneysIndexRoute
  '/laws': typeof LayoutLawsIndexRoute
  '/portfolio': typeof LayoutPortfolioIndexRoute
  '/professionals': typeof LayoutProfessionalsIndexRoute
  '/journeys/$journeyId/property-evaluation': typeof LayoutJourneysJourneyIdPropertyEvaluationRoute
  '/journeys/$journeyId': typeof LayoutJourneysJourneyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tools': typeof ToolsRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/calculators': typeof LayoutCalculatorsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/tools/mortgage-calculator': typeof ToolsMortgageCalculatorRoute
  '/tools/property-cost-calculator': typeof ToolsPropertyCostCalculatorRoute
  '/tools/roi-calculator': typeof ToolsRoiCalculatorRoute
  '/tools/': typeof ToolsIndexRoute
  '/_layout/articles/$slug': typeof LayoutArticlesSlugRoute
  '/_layout/documents/$documentId': typeof LayoutDocumentsDocumentIdRoute
  '/_layout/glossary/$slug': typeof LayoutGlossarySlugRoute
  '/_layout/journeys/$journeyId': typeof LayoutJourneysJourneyIdRouteWithChildren
  '/_layout/journeys/new': typeof LayoutJourneysNewRoute
  '/_layout/laws/$lawId': typeof LayoutLawsLawIdRoute
  '/_layout/laws/bookmarks': typeof LayoutLawsBookmarksRoute
  '/_layout/portfolio/$propertyId': typeof LayoutPortfolioPropertyIdRoute
  '/_layout/professionals/$professionalId': typeof LayoutProfessionalsProfessionalIdRoute
  '/shared/evaluation/$shareId': typeof SharedEvaluationShareIdRoute
  '/_layout/articles/': typeof LayoutArticlesIndexRoute
  '/_layout/documents/': typeof LayoutDocumentsIndexRoute
  '/_layout/glossary/': typeof LayoutGlossaryIndexRoute
  '/_layout/journeys/': typeof LayoutJourneysIndexRoute
  '/_layout/laws/': typeof LayoutLawsIndexRoute
  '/_layout/portfolio/': typeof LayoutPortfolioIndexRoute
  '/_layout/professionals/': typeof LayoutProfessionalsIndexRoute
  '/_layout/journeys/$journeyId/property-evaluation': typeof LayoutJourneysJourneyIdPropertyEvaluationRoute
  '/_layout/journeys/$journeyId/': typeof LayoutJourneysJourneyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/tools'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin'
    | '/calculators'
    | '/dashboard'
    | '/items'
    | '/search'
    | '/settings'
    | '/tools/mortgage-calculator'
    | '/tools/property-cost-calculator'
    | '/tools/roi-calculator'
    | '/tools/'
    | '/articles/$slug'
    | '/documents/$documentId'
    | '/glossary/$slug'
    | '/journeys/$journeyId'
    | '/journeys/new'
    | '/laws/$lawId'
    | '/laws/bookmarks'
    | '/portfolio/$propertyId'
    | '/professionals/$professionalId'
    | '/shared/evaluation/$shareId'
    | '/articles/'
    | '/documents/'
    | '/glossary/'
    | '/journeys/'
    | '/laws/'
    | '/portfolio/'
    | '/professionals/'
    | '/journeys/$journeyId/property-evaluation'
    | '/journeys/$journeyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin'
    | '/calculators'
    | '/dashboard'
    | '/items'
    | '/search'
    | '/settings'
    | '/tools/mortgage-calculator'
    | '/tools/property-cost-calculator'
    | '/tools/roi-calculator'
    | '/tools'
    | '/articles/$slug'
    | '/documents/$documentId'
    | '/glossary/$slug'
    | '/journeys/new'
    | '/laws/$lawId'
    | '/laws/bookmarks'
    | '/portfolio/$propertyId'
    | '/professionals/$professionalId'
    | '/shared/evaluation/$shareId'
    | '/articles'
    | '/documents'
    | '/glossary'
    | '/journeys'
    | '/laws'
    | '/portfolio'
    | '/professionals'
    | '/journeys/$journeyId/property-evaluation'
    | '/journeys/$journeyId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/tools'
    | '/unsubscribe'
    | '/verify-email'
    | '/_layout/admin'
    | '/_layout/calculators'
    | '/_layout/dashboard'
    | '/_layout/items'
    | '/_layout/search'
    | '/_layout/settings'
    | '/tools/mortgage-calculator'
    | '/tools/property-cost-calculator'
    | '/tools/roi-calculator'
    | '/tools/'
    | '/_layout/articles/$slug'
    | '/_layout/documents/$documentId'
    | '/_layout/glossary/$slug'
    | '/_layout/journeys/$journeyId'
    | '/_layout/journeys/new'
    | '/_layout/laws/$lawId'
    | '/_layout/laws/bookmarks'
    | '/_layout/portfolio/$propertyId'
    | '/_layout/professionals/$professionalId'
    | '/shared/evaluation/$shareId'
    | '/_layout/articles/'
    | '/_layout/documents/'
    | '/_layout/glossary/'
    | '/_layout/journeys/'
    | '/_layout/laws/'
    | '/_layout/portfolio/'
    | '/_layout/professionals/'
    | '/_layout/journeys/$journeyId/property-evaluation'
    | '/_layout/journeys/$journeyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  SharedEvaluationShareIdRoute: typeof SharedEvaluationShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/roi-calculator': {
      id: '/tools/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/tools/roi-calculator'
      preLoaderRoute: typeof ToolsRoiCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/property-cost-calculator': {
      id: '/tools/property-cost-calculator'
      path: '/property-cost-calculator'
      fullPath: '/tools/property-cost-calculator'
      preLoaderRoute: typeof ToolsPropertyCostCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/mortgage-calculator': {
      id: '/tools/mortgage-calculator'
      path: '/mortgage-calculator'
      fullPath: '/tools/mortgage-calculator'
      preLoaderRoute: typeof ToolsMortgageCalculatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/calculators': {
      id: '/_layout/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof LayoutCalculatorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/professionals/': {
      id: '/_layout/professionals/'
      path: '/professionals'
      fullPath: '/professionals/'
      preLoaderRoute: typeof LayoutProfessionalsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio/': {
      id: '/_layout/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof LayoutPortfolioIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/laws/': {
      id: '/_layout/laws/'
      path: '/laws'
      fullPath: '/laws/'
      preLoaderRoute: typeof LayoutLawsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/': {
      id: '/_layout/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof LayoutJourneysIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/glossary/': {
      id: '/_layout/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof LayoutGlossaryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documents/': {
      id: '/_layout/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof LayoutDocumentsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/articles/': {
      id: '/_layout/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof LayoutArticlesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/shared/evaluation/$shareId': {
      id: '/shared/evaluation/$shareId'
      path: '/shared/evaluation/$shareId'
      fullPath: '/shared/evaluation/$shareId'
      preLoaderRoute: typeof SharedEvaluationShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/professionals/$professionalId': {
      id: '/_layout/professionals/$professionalId'
      path: '/professionals/$professionalId'
      fullPath: '/professionals/$professionalId'
      preLoaderRoute: typeof LayoutProfessionalsProfessionalIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio/$propertyId': {
      id: '/_layout/portfolio/$propertyId'
      path: '/portfolio/$propertyId'
      fullPath: '/portfolio/$propertyId'
      preLoaderRoute: typeof LayoutPortfolioPropertyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/laws/bookmarks': {
      id: '/_layout/laws/bookmarks'
      path: '/laws/bookmarks'
      fullPath: '/laws/bookmarks'
      preLoaderRoute: typeof LayoutLawsBookmarksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/laws/$lawId': {
      id: '/_layout/laws/$lawId'
      path: '/laws/$lawId'
      fullPath: '/laws/$lawId'
      preLoaderRoute: typeof LayoutLawsLawIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/new': {
      id: '/_layout/journeys/new'
      path: '/journeys/new'
      fullPath: '/journeys/new'
      preLoaderRoute: typeof LayoutJourneysNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/$journeyId': {
      id: '/_layout/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof LayoutJourneysJourneyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/glossary/$slug': {
      id: '/_layout/glossary/$slug'
      path: '/glossary/$slug'
      fullPath: '/glossary/$slug'
      preLoaderRoute: typeof LayoutGlossarySlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documents/$documentId': {
      id: '/_layout/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof LayoutDocumentsDocumentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/articles/$slug': {
      id: '/_layout/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof LayoutArticlesSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/journeys/$journeyId/': {
      id: '/_layout/journeys/$journeyId/'
      path: '/'
      fullPath: '/journeys/$journeyId/'
      preLoaderRoute: typeof LayoutJourneysJourneyIdIndexRouteImport
      parentRoute: typeof LayoutJourneysJourneyIdRoute
    }
    '/_layout/journeys/$journeyId/property-evaluation': {
      id: '/_layout/journeys/$journeyId/property-evaluation'
      path: '/property-evaluation'
      fullPath: '/journeys/$journeyId/property-evaluation'
      preLoaderRoute: typeof LayoutJourneysJourneyIdPropertyEvaluationRouteImport
      parentRoute: typeof LayoutJourneysJourneyIdRoute
    }
  }
}

interface LayoutJourneysJourneyIdRouteChildren {
  LayoutJourneysJourneyIdPropertyEvaluationRoute: typeof LayoutJourneysJourneyIdPropertyEvaluationRoute
  LayoutJourneysJourneyIdIndexRoute: typeof LayoutJourneysJourneyIdIndexRoute
}

const LayoutJourneysJourneyIdRouteChildren: LayoutJourneysJourneyIdRouteChildren =
  {
    LayoutJourneysJourneyIdPropertyEvaluationRoute:
      LayoutJourneysJourneyIdPropertyEvaluationRoute,
    LayoutJourneysJourneyIdIndexRoute: LayoutJourneysJourneyIdIndexRoute,
  }

const LayoutJourneysJourneyIdRouteWithChildren =
  LayoutJourneysJourneyIdRoute._addFileChildren(
    LayoutJourneysJourneyIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCalculatorsRoute: typeof LayoutCalculatorsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutArticlesSlugRoute: typeof LayoutArticlesSlugRoute
  LayoutDocumentsDocumentIdRoute: typeof LayoutDocumentsDocumentIdRoute
  LayoutGlossarySlugRoute: typeof LayoutGlossarySlugRoute
  LayoutJourneysJourneyIdRoute: typeof LayoutJourneysJourneyIdRouteWithChildren
  LayoutJourneysNewRoute: typeof LayoutJourneysNewRoute
  LayoutLawsLawIdRoute: typeof LayoutLawsLawIdRoute
  LayoutLawsBookmarksRoute: typeof LayoutLawsBookmarksRoute
  LayoutPortfolioPropertyIdRoute: typeof LayoutPortfolioPropertyIdRoute
  LayoutProfessionalsProfessionalIdRoute: typeof LayoutProfessionalsProfessionalIdRoute
  LayoutArticlesIndexRoute: typeof LayoutArticlesIndexRoute
  LayoutDocumentsIndexRoute: typeof LayoutDocumentsIndexRoute
  LayoutGlossaryIndexRoute: typeof LayoutGlossaryIndexRoute
  LayoutJourneysIndexRoute: typeof LayoutJourneysIndexRoute
  LayoutLawsIndexRoute: typeof LayoutLawsIndexRoute
  LayoutPortfolioIndexRoute: typeof LayoutPortfolioIndexRoute
  LayoutProfessionalsIndexRoute: typeof LayoutProfessionalsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCalculatorsRoute: LayoutCalculatorsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutArticlesSlugRoute: LayoutArticlesSlugRoute,
  LayoutDocumentsDocumentIdRoute: LayoutDocumentsDocumentIdRoute,
  LayoutGlossarySlugRoute: LayoutGlossarySlugRoute,
  LayoutJourneysJourneyIdRoute: LayoutJourneysJourneyIdRouteWithChildren,
  LayoutJourneysNewRoute: LayoutJourneysNewRoute,
  LayoutLawsLawIdRoute: LayoutLawsLawIdRoute,
  LayoutLawsBookmarksRoute: LayoutLawsBookmarksRoute,
  LayoutPortfolioPropertyIdRoute: LayoutPortfolioPropertyIdRoute,
  LayoutProfessionalsProfessionalIdRoute:
    LayoutProfessionalsProfessionalIdRoute,
  LayoutArticlesIndexRoute: LayoutArticlesIndexRoute,
  LayoutDocumentsIndexRoute: LayoutDocumentsIndexRoute,
  LayoutGlossaryIndexRoute: LayoutGlossaryIndexRoute,
  LayoutJourneysIndexRoute: LayoutJourneysIndexRoute,
  LayoutLawsIndexRoute: LayoutLawsIndexRoute,
  LayoutPortfolioIndexRoute: LayoutPortfolioIndexRoute,
  LayoutProfessionalsIndexRoute: LayoutProfessionalsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ToolsRouteChildren {
  ToolsMortgageCalculatorRoute: typeof ToolsMortgageCalculatorRoute
  ToolsPropertyCostCalculatorRoute: typeof ToolsPropertyCostCalculatorRoute
  ToolsRoiCalculatorRoute: typeof ToolsRoiCalculatorRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsMortgageCalculatorRoute: ToolsMortgageCalculatorRoute,
  ToolsPropertyCostCalculatorRoute: ToolsPropertyCostCalculatorRoute,
  ToolsRoiCalculatorRoute: ToolsRoiCalculatorRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  SharedEvaluationShareIdRoute: SharedEvaluationShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
